pub use self::template::ItemTemplate;
pub use self::ammunition::AmmunitionTemplate;
pub use self::amulet::AmuletTemplate;
pub use self::armor::ArmorTemplate;
pub use self::axe::AxeTemplate;
pub use self::bag::BagTemplate;
pub use self::belt::BeltTemplate;
pub use self::boots::BootsTemplate;
pub use self::bow::BowTemplate;
pub use self::bracers::BracersTemplate;
pub use self::chest::ChestTemplate;
pub use self::chime::ChimeTemplate;
pub use self::cloak::CloakTemplate;
pub use self::crossbow::CrossbowTemplate;
pub use self::dagger::DaggerTemplate;
pub use self::food::FoodTemplate;
pub use self::gloves::GlovesTemplate;
pub use self::helm::HelmTemplate;
pub use self::horn::HornTemplate;
pub use self::instrument::InstrumentTemplate;
pub use self::inn::LodgingAtInnTemplate;
pub use self::junk_food::JunkFoodTemplate;
pub use self::light_source::LightSourceTemplate;
pub use self::mace::MaceTemplate;
pub use self::magic_book::MagicBookTemplate;
pub use self::misc::MiscTemplate;
pub use self::misc_usable::MiscUsableTemplate;
pub use self::pick::PickTemplate;
pub use self::polearm::PolearmTemplate;
pub use self::potion::PotionTemplate;
pub use self::prayer_book::PrayerBookTemplate;
pub use self::ring::RingTemplate;
pub use self::scroll::ScrollTemplate;
pub use self::shield::ShieldTemplate;
pub use self::sling::SlingTemplate;
pub use self::song_book::SongBookTemplate;
pub use self::staff::StaffTemplate;
pub use self::sword::SwordTemplate;
pub use self::valuable::ValuableTemplate;
pub use self::wand::WandTemplate;

mod ammunition;
mod amulet;
mod armor;
mod axe;
mod bag;
mod belt;
mod boots;
mod bow;
mod bracers;
mod chest;
mod chime;
mod cloak;
mod crossbow;
mod dagger;
mod food;
mod gloves;
mod helm;
mod horn;
mod inn;
mod instrument;
mod junk_food;
mod light_source;
mod mace;
mod magic_book;
mod misc;
mod misc_usable;
mod pick;
mod polearm;
mod potion;
mod prayer_book;
mod ring;
mod scroll;
mod shield;
mod sling;
mod song_book;
mod staff;
mod sword;
mod template;
mod valuable;
mod wand;
