use model;
use item_template;

#[derive(Copy, Clone, Eq, PartialEq, Hash)]
pub enum PotionTemplate {
    AppleJuice,
    Blindness,
    Boldliness,
    Charisma,
    Confusion,
    CureCriticalWounds,
    CureLightWounds,
    CureSeriousWounds,
    DetectInvisible,
    FleaBile,
    GainConstitution,
    GainDexterity,
    GainExperience,
    GainIntelligence,
    GainStrength,
    GainWisdom,
    HasteSelf,
    Healing,
    Heroism,
    InfraVision,
    Invulnerability,
    Learning,
    LoseIntelligence,
    LoseMemories,
    LoseWisdom,
    NeutralizePoison,
    Poison,
    ResistCold,
    ResistHeat,
    RestoreCharisma,
    RestoreConstitution,
    RestoreDexterity,
    RestoreIntelligence,
    RestoreLifeLevels,
    RestoreMana,
    RestoreStrength,
    RestoreWisdom,
    SaltWater,
    Sleep,
    SlimeMoldJuice,
    SlowPoison,
    Slowness,
    SuperHeroism,
    Ugliness,
    Water,
}

impl PotionTemplate {
    pub fn vec() -> Vec<Box<dyn item_template::ItemTemplate>> {
        vec![
            Box::new(PotionTemplate::AppleJuice),
            Box::new(PotionTemplate::Blindness),
            Box::new(PotionTemplate::Boldliness),
            Box::new(PotionTemplate::Charisma),
            Box::new(PotionTemplate::Confusion),
            Box::new(PotionTemplate::CureCriticalWounds),
            Box::new(PotionTemplate::CureLightWounds),
            Box::new(PotionTemplate::CureSeriousWounds),
            Box::new(PotionTemplate::DetectInvisible),
            Box::new(PotionTemplate::FleaBile),
            Box::new(PotionTemplate::GainConstitution),
            Box::new(PotionTemplate::GainDexterity),
            Box::new(PotionTemplate::GainExperience),
            Box::new(PotionTemplate::GainIntelligence),
            Box::new(PotionTemplate::GainStrength),
            Box::new(PotionTemplate::GainWisdom),
            Box::new(PotionTemplate::HasteSelf),
            Box::new(PotionTemplate::Healing),
            Box::new(PotionTemplate::Heroism),
            Box::new(PotionTemplate::InfraVision),
            Box::new(PotionTemplate::Invulnerability),
            Box::new(PotionTemplate::Learning),
            Box::new(PotionTemplate::LoseIntelligence),
            Box::new(PotionTemplate::LoseMemories),
            Box::new(PotionTemplate::LoseWisdom),
            Box::new(PotionTemplate::NeutralizePoison),
            Box::new(PotionTemplate::Poison),
            Box::new(PotionTemplate::ResistCold),
            Box::new(PotionTemplate::ResistHeat),
            Box::new(PotionTemplate::RestoreCharisma),
            Box::new(PotionTemplate::RestoreConstitution),
            Box::new(PotionTemplate::RestoreDexterity),
            Box::new(PotionTemplate::RestoreIntelligence),
            Box::new(PotionTemplate::RestoreLifeLevels),
            Box::new(PotionTemplate::RestoreMana),
            Box::new(PotionTemplate::RestoreStrength),
            Box::new(PotionTemplate::RestoreWisdom),
            Box::new(PotionTemplate::SaltWater),
            Box::new(PotionTemplate::Sleep),
            Box::new(PotionTemplate::SlimeMoldJuice),
            Box::new(PotionTemplate::SlowPoison),
            Box::new(PotionTemplate::Slowness),
            Box::new(PotionTemplate::SuperHeroism),
            Box::new(PotionTemplate::Ugliness),
            Box::new(PotionTemplate::Water),
        ]
    }

    pub fn iter() -> impl Iterator<Item=Box<dyn item_template::ItemTemplate>> {
        PotionTemplate::vec().into_iter()
    }

    pub fn from(subval: i64) -> Box<dyn item_template::ItemTemplate> {
        match subval {
            276 => Box::new(PotionTemplate::Blindness),
            293 => Box::new(PotionTemplate::Boldliness),
            266 => Box::new(PotionTemplate::Charisma),
            277 => Box::new(PotionTemplate::Confusion),
            271 => Box::new(PotionTemplate::CureCriticalWounds),
            269 => Box::new(PotionTemplate::CureLightWounds),
            270 => Box::new(PotionTemplate::CureSeriousWounds),
            297 => Box::new(PotionTemplate::DetectInvisible),
            302 => Box::new(PotionTemplate::FleaBile),
            273 => Box::new(PotionTemplate::GainConstitution),
            284 => Box::new(PotionTemplate::GainDexterity),
            274 => Box::new(PotionTemplate::GainExperience),
            260 => Box::new(PotionTemplate::GainIntelligence),
            257 => Box::new(PotionTemplate::GainStrength),
            263 => Box::new(PotionTemplate::GainWisdom),
            279 => Box::new(PotionTemplate::HasteSelf),
            272 => Box::new(PotionTemplate::Healing),
            291 => Box::new(PotionTemplate::Heroism),
            301 => Box::new(PotionTemplate::InfraVision),
            290 => Box::new(PotionTemplate::Invulnerability),
            287 => Box::new(PotionTemplate::Learning),
            261 => Box::new(PotionTemplate::LoseIntelligence),
            288 => Box::new(PotionTemplate::LoseMemories),
            264 => Box::new(PotionTemplate::LoseWisdom),
            299 => Box::new(PotionTemplate::NeutralizePoison),
            258 => Box::new(PotionTemplate::Poison),
            296 => Box::new(PotionTemplate::ResistCold),
            295 => Box::new(PotionTemplate::ResistHeat),
            268 => Box::new(PotionTemplate::RestoreCharisma),
            286 => Box::new(PotionTemplate::RestoreConstitution),
            285 => Box::new(PotionTemplate::RestoreDexterity),
            262 => Box::new(PotionTemplate::RestoreIntelligence),
            294 => Box::new(PotionTemplate::RestoreLifeLevels),
            300 => Box::new(PotionTemplate::RestoreMana),
            259 => Box::new(PotionTemplate::RestoreStrength),
            265 => Box::new(PotionTemplate::RestoreWisdom),
            289 => Box::new(PotionTemplate::SaltWater),
            275 => Box::new(PotionTemplate::Sleep),
            298 => Box::new(PotionTemplate::SlowPoison),
            280 => Box::new(PotionTemplate::Slowness),
            292 => Box::new(PotionTemplate::SuperHeroism),
            267 => Box::new(PotionTemplate::Ugliness),
            283 => Box::new(PotionTemplate::Water),
            281 => Box::new(PotionTemplate::SlimeMoldJuice),
            282 => Box::new(PotionTemplate::AppleJuice),
            _ => panic!("subval {} out of bounds", subval),
        }
    }
}

impl item_template::ItemTemplate for PotionTemplate {
    fn item_type(&self) -> model::ItemType { model::ItemType::Potion }

    fn flags1(&self) -> u64 {
        match self {
            PotionTemplate::Blindness => 0x00000000,
            PotionTemplate::Boldliness => 0x00000020,
            PotionTemplate::Charisma => 0x00000000,
            PotionTemplate::Confusion => 0x00000000,
            PotionTemplate::CureCriticalWounds => 0x00000000,
            PotionTemplate::CureLightWounds => 0x00000000,
            PotionTemplate::CureSeriousWounds => 0x00000000,
            PotionTemplate::DetectInvisible => 0x00000200,
            PotionTemplate::FleaBile => 0x00004000,
            PotionTemplate::GainConstitution => 0x00000000,
            PotionTemplate::GainDexterity => 0x00000000,
            PotionTemplate::GainExperience => 0x00000000,
            PotionTemplate::GainIntelligence => 0x00000000,
            PotionTemplate::GainStrength => 0x00000000,
            PotionTemplate::GainWisdom => 0x00000000,
            PotionTemplate::HasteSelf => 0x00000000,
            PotionTemplate::Healing => 0x00000000,
            PotionTemplate::Heroism => 0x00000008,
            PotionTemplate::InfraVision => 0x00002000,
            PotionTemplate::Invulnerability => 0x00000004,
            PotionTemplate::Learning => 0x00008000,
            PotionTemplate::LoseIntelligence => 0x00000000,
            PotionTemplate::LoseMemories => 0x00000001,
            PotionTemplate::LoseWisdom => 0x00000000,
            PotionTemplate::NeutralizePoison => 0x00000800,
            PotionTemplate::Poison => 0x00000000,
            PotionTemplate::ResistCold => 0x00000100,
            PotionTemplate::ResistHeat => 0x00000080,
            PotionTemplate::RestoreCharisma => 0x00000000,
            PotionTemplate::RestoreConstitution => 0x00000000,
            PotionTemplate::RestoreDexterity => 0x00010000,
            PotionTemplate::RestoreIntelligence => 0x00000000,
            PotionTemplate::RestoreLifeLevels => 0x00000040,
            PotionTemplate::RestoreMana => 0x00001000,
            PotionTemplate::RestoreStrength => 0x00000000,
            PotionTemplate::RestoreWisdom => 0x00000000,
            PotionTemplate::SaltWater => 0x00000002,
            PotionTemplate::Sleep => 0x00000000,
            PotionTemplate::SlowPoison => 0x00000400,
            PotionTemplate::Slowness => 0x00000000,
            PotionTemplate::SuperHeroism => 0x00000010,
            PotionTemplate::Ugliness => 0x00000000,
            PotionTemplate::Water => 0x00000000,
            PotionTemplate::SlimeMoldJuice => 0x00000000,
            PotionTemplate::AppleJuice => 0x00000000,
        }
    }

    fn flags2(&self) -> u64 {
        match self {
            PotionTemplate::Blindness => 0x00080000,
            PotionTemplate::Boldliness => 0x00000000,
            PotionTemplate::Charisma => 0x00000200,
            PotionTemplate::Confusion => 0x00100000,
            PotionTemplate::CureCriticalWounds => 0x70004000,
            PotionTemplate::CureLightWounds => 0x10001000,
            PotionTemplate::CureSeriousWounds => 0x30002000,
            PotionTemplate::DetectInvisible => 0x00000000,
            PotionTemplate::FleaBile => 0x00000000,
            PotionTemplate::GainConstitution => 0x00010000,
            PotionTemplate::GainDexterity => 0x02000000,
            PotionTemplate::GainExperience => 0x00020000,
            PotionTemplate::GainIntelligence => 0x00000008,
            PotionTemplate::GainStrength => 0x00000001,
            PotionTemplate::GainWisdom => 0x00000040,
            PotionTemplate::HasteSelf => 0x00400000,
            PotionTemplate::Healing => 0x70008000,
            PotionTemplate::Heroism => 0x00000000,
            PotionTemplate::InfraVision => 0x00000000,
            PotionTemplate::Invulnerability => 0x00000000,
            PotionTemplate::Learning => 0x00000000,
            PotionTemplate::LoseIntelligence => 0x00000010,
            PotionTemplate::LoseMemories => 0x00000000,
            PotionTemplate::LoseWisdom => 0x00000080,
            PotionTemplate::NeutralizePoison => 0x00000000,
            PotionTemplate::Poison => 0x00000002,
            PotionTemplate::ResistCold => 0x00000000,
            PotionTemplate::ResistHeat => 0x00000000,
            PotionTemplate::RestoreCharisma => 0x00000800,
            PotionTemplate::RestoreConstitution => 0x68000000,
            PotionTemplate::RestoreDexterity => 0x04000000,
            PotionTemplate::RestoreIntelligence => 0x00000020,
            PotionTemplate::RestoreLifeLevels => 0x00000000,
            PotionTemplate::RestoreMana => 0x00000000,
            PotionTemplate::RestoreStrength => 0x00000004,
            PotionTemplate::RestoreWisdom => 0x00000100,
            PotionTemplate::SaltWater => 0x00000000,
            PotionTemplate::Sleep => 0x10040000,
            PotionTemplate::SlowPoison => 0x00000000,
            PotionTemplate::Slowness => 0x00800000,
            PotionTemplate::SuperHeroism => 0x00000000,
            PotionTemplate::Ugliness => 0x00000400,
            PotionTemplate::Water => 0x00800000,
            PotionTemplate::SlimeMoldJuice => 0x30000000,
            PotionTemplate::AppleJuice => 0x00800000,
        }
    }

    fn p1(&self) -> i64 {
        match self {
            PotionTemplate::Blindness => 0,
            PotionTemplate::Boldliness => 0,
            PotionTemplate::Charisma => 0,
            PotionTemplate::Confusion => 50,
            PotionTemplate::CureCriticalWounds => 100,
            PotionTemplate::CureLightWounds => 50,
            PotionTemplate::CureSeriousWounds => 100,
            PotionTemplate::DetectInvisible => 0,
            PotionTemplate::FleaBile => 0,
            PotionTemplate::GainConstitution => 0,
            PotionTemplate::GainDexterity => 0,
            PotionTemplate::GainExperience => 0,
            PotionTemplate::GainIntelligence => 0,
            PotionTemplate::GainStrength => 0,
            PotionTemplate::GainWisdom => 0,
            PotionTemplate::HasteSelf => 0,
            PotionTemplate::Healing => 200,
            PotionTemplate::Heroism => 0,
            PotionTemplate::InfraVision => 0,
            PotionTemplate::Invulnerability => 0,
            PotionTemplate::Learning => 0,
            PotionTemplate::LoseIntelligence => 0,
            PotionTemplate::LoseMemories => 0,
            PotionTemplate::LoseWisdom => 0,
            PotionTemplate::NeutralizePoison => 0,
            PotionTemplate::Poison => 0,
            PotionTemplate::ResistCold => 0,
            PotionTemplate::ResistHeat => 0,
            PotionTemplate::RestoreCharisma => 0,
            PotionTemplate::RestoreConstitution => 0,
            PotionTemplate::RestoreDexterity => 0,
            PotionTemplate::RestoreIntelligence => 0,
            PotionTemplate::RestoreLifeLevels => 0,
            PotionTemplate::RestoreMana => 0,
            PotionTemplate::RestoreStrength => 0,
            PotionTemplate::RestoreWisdom => 0,
            PotionTemplate::SaltWater => 0,
            PotionTemplate::Sleep => 100,
            PotionTemplate::SlowPoison => 0,
            PotionTemplate::Slowness => 50,
            PotionTemplate::SuperHeroism => 0,
            PotionTemplate::Ugliness => 0,
            PotionTemplate::Water => 200,
            PotionTemplate::SlimeMoldJuice => 400,
            PotionTemplate::AppleJuice => 250,
        }
    }

    fn cost(&self) -> i64 {
        match self {
            PotionTemplate::Blindness => 0,
            PotionTemplate::Boldliness => 10,
            PotionTemplate::Charisma => 6500,
            PotionTemplate::Confusion => 0,
            PotionTemplate::CureCriticalWounds => 100,
            PotionTemplate::CureLightWounds => 15,
            PotionTemplate::CureSeriousWounds => 40,
            PotionTemplate::DetectInvisible => 50,
            PotionTemplate::FleaBile => 50,
            PotionTemplate::GainConstitution => 6500,
            PotionTemplate::GainDexterity => 6500,
            PotionTemplate::GainExperience => 15000,
            PotionTemplate::GainIntelligence => 6500,
            PotionTemplate::GainStrength => 6500,
            PotionTemplate::GainWisdom => 6500,
            PotionTemplate::HasteSelf => 155,
            PotionTemplate::Healing => 2500,
            PotionTemplate::Heroism => 35,
            PotionTemplate::InfraVision => 20,
            PotionTemplate::Invulnerability => 12500,
            PotionTemplate::Learning => 200,
            PotionTemplate::LoseIntelligence => 0,
            PotionTemplate::LoseMemories => 0,
            PotionTemplate::LoseWisdom => 0,
            PotionTemplate::NeutralizePoison => 75,
            PotionTemplate::Poison => 0,
            PotionTemplate::ResistCold => 30,
            PotionTemplate::ResistHeat => 30,
            PotionTemplate::RestoreCharisma => 300,
            PotionTemplate::RestoreConstitution => 300,
            PotionTemplate::RestoreDexterity => 300,
            PotionTemplate::RestoreIntelligence => 300,
            PotionTemplate::RestoreLifeLevels => 400,
            PotionTemplate::RestoreMana => 3000,
            PotionTemplate::RestoreStrength => 300,
            PotionTemplate::RestoreWisdom => 300,
            PotionTemplate::SaltWater => 0,
            PotionTemplate::Sleep => 0,
            PotionTemplate::SlowPoison => 25,
            PotionTemplate::Slowness => 0,
            PotionTemplate::SuperHeroism => 100,
            PotionTemplate::Ugliness => 0,
            PotionTemplate::Water => 0,
            PotionTemplate::SlimeMoldJuice => 2,
            PotionTemplate::AppleJuice => 1,
        }
    }

    fn subtype(&self) -> i64 {
        match self {
            PotionTemplate::Blindness => 276,
            PotionTemplate::Boldliness => 293,
            PotionTemplate::Charisma => 266,
            PotionTemplate::Confusion => 277,
            PotionTemplate::CureCriticalWounds => 271,
            PotionTemplate::CureLightWounds => 269,
            PotionTemplate::CureSeriousWounds => 270,
            PotionTemplate::DetectInvisible => 297,
            PotionTemplate::FleaBile => 302,
            PotionTemplate::GainConstitution => 273,
            PotionTemplate::GainDexterity => 284,
            PotionTemplate::GainExperience => 274,
            PotionTemplate::GainIntelligence => 260,
            PotionTemplate::GainStrength => 257,
            PotionTemplate::GainWisdom => 263,
            PotionTemplate::HasteSelf => 279,
            PotionTemplate::Healing => 272,
            PotionTemplate::Heroism => 291,
            PotionTemplate::InfraVision => 301,
            PotionTemplate::Invulnerability => 290,
            PotionTemplate::Learning => 287,
            PotionTemplate::LoseIntelligence => 261,
            PotionTemplate::LoseMemories => 288,
            PotionTemplate::LoseWisdom => 264,
            PotionTemplate::NeutralizePoison => 299,
            PotionTemplate::Poison => 258,
            PotionTemplate::ResistCold => 296,
            PotionTemplate::ResistHeat => 295,
            PotionTemplate::RestoreCharisma => 268,
            PotionTemplate::RestoreConstitution => 286,
            PotionTemplate::RestoreDexterity => 285,
            PotionTemplate::RestoreIntelligence => 262,
            PotionTemplate::RestoreLifeLevels => 294,
            PotionTemplate::RestoreMana => 300,
            PotionTemplate::RestoreStrength => 259,
            PotionTemplate::RestoreWisdom => 265,
            PotionTemplate::SaltWater => 289,
            PotionTemplate::Sleep => 275,
            PotionTemplate::SlowPoison => 298,
            PotionTemplate::Slowness => 280,
            PotionTemplate::SuperHeroism => 292,
            PotionTemplate::Ugliness => 267,
            PotionTemplate::Water => 283,
            PotionTemplate::SlimeMoldJuice => 281,
            PotionTemplate::AppleJuice => 282,
        }
    }

    fn weight(&self) -> u16 { 4 }
    fn number(&self) -> u16 { 1 }
    fn modifier_to_hit(&self) -> i16 { 0 }
    fn modifier_to_damage(&self) -> i16 { 0 }
    fn base_ac(&self) -> i16 { 0 }
    fn modifier_to_ac(&self) -> i16 { 0 }
    fn damage(&self) -> &str { "1d1" }

    fn item_level(&self) -> u8 {
        match self {
            PotionTemplate::SaltWater => 0,
            PotionTemplate::FleaBile => 0,
            PotionTemplate::Blindness => 0,
            PotionTemplate::Confusion => 0,
            PotionTemplate::CureLightWounds => 0,
            PotionTemplate::Water => 0,
            PotionTemplate::Sleep => 0,
            PotionTemplate::SlimeMoldJuice => 0,
            PotionTemplate::AppleJuice => 0,
            PotionTemplate::ResistCold => 1,
            PotionTemplate::HasteSelf => 1,
            PotionTemplate::Boldliness => 1,
            PotionTemplate::ResistHeat => 1,
            PotionTemplate::Heroism => 1,
            PotionTemplate::SlowPoison => 1,
            PotionTemplate::Slowness =>  1,
            PotionTemplate::CureSeriousWounds => 3,
            PotionTemplate::DetectInvisible => 3,
            PotionTemplate::InfraVision => 3,
            PotionTemplate::Poison => 3,
            PotionTemplate::SuperHeroism => 3,
            PotionTemplate::NeutralizePoison => 5,
            PotionTemplate::CureCriticalWounds => 5,
            PotionTemplate::LoseMemories => 10,
            PotionTemplate::Healing => 12,
            PotionTemplate::Charisma => 25,
            PotionTemplate::Ugliness => 25,
            PotionTemplate::GainConstitution => 25,
            PotionTemplate::GainDexterity => 25,
            PotionTemplate::GainIntelligence => 25,
            PotionTemplate::GainStrength => 25,
            PotionTemplate::GainWisdom => 25,
            PotionTemplate::LoseIntelligence => 25,
            PotionTemplate::RestoreMana => 25,
            PotionTemplate::LoseWisdom =>  25,
            PotionTemplate::RestoreCharisma => 40,
            PotionTemplate::RestoreConstitution => 40,
            PotionTemplate::RestoreDexterity => 40,
            PotionTemplate::RestoreIntelligence => 40,
            PotionTemplate::RestoreStrength => 40,
            PotionTemplate::RestoreWisdom => 40,
            PotionTemplate::RestoreLifeLevels => 40,
            PotionTemplate::Invulnerability => 40,
            PotionTemplate::Learning => 45,
            PotionTemplate::GainExperience => 50,
        }
    }

    fn is_identified(&self) -> bool { false }
}
