pub type Damage = [libc::c_char; 7];
pub type Name = [libc::c_char; 70];

pub use self::ability::*;
pub use self::cave::*;
pub use self::class::*;
pub use self::currency::*;
pub use self::dungeon_record::*;
pub use self::gametime::*;
pub use self::identified_record::*;
pub use self::inven_record::*;
pub use self::inventory_item::*;
pub use self::item::*;
pub use self::item_type::*;
pub use self::magic::*;
pub use self::monster::*;
pub use self::monster_record::*;
pub use self::monster_template::*;
pub use self::player::*;
pub use self::player_flags::*;
pub use self::player_record::*;
pub use self::race::*;
pub use self::sex::*;
pub use self::spell::*;
pub use self::stat::*;
pub use self::statblock::*;
pub use self::store::*;
pub use self::time::*;
pub use self::town_record::*;
pub use self::treasure_and_coordinate::*;
pub use self::wallet::*;

mod ability;
mod cave;
mod class;
mod currency;
mod dungeon_record;
mod gametime;
mod identified_record;
mod inven_record;
mod inventory_item;
mod item;
mod item_type;
mod magic;
mod monster;
mod monster_record;
mod monster_template;
mod player;
mod player_flags;
mod player_record;
mod race;
mod sex;
mod spell;
mod stat;
mod statblock;
mod store;
mod time;
mod town_record;
mod treasure_and_coordinate;
mod wallet;
