pub type Damage = [libc::c_char; 7];
pub type Name = [libc::c_char; 70];

pub use self::ability::*;
pub use self::class::*;
pub use self::currency::*;
pub use self::gametime::*;
pub use self::item::*;
pub use self::item_type::*;
pub use self::magic::*;
pub use self::monster::*;
pub use self::race::*;
pub use self::sex::*;
pub use self::spell::*;
pub use self::stat::*;
pub use self::statblock::*;
pub use self::wallet::*;

mod ability;
mod class;
mod class_interop;
mod currency;
mod gametime;
mod item;
mod item_interop;
mod item_type;
mod magic;
mod monster;
mod race;
mod sex;
mod spell;
mod stat;
mod statblock;
mod wallet;
