use libc;

use crate::model::{Class, GameTime, Player, PlayerFlags, Race, Sex, Time, Wallet};

#[repr(C)]
#[derive(Serialize, Deserialize)]
pub struct PlayerRecord {
    pub uid: i64,
    pub account: i64,
    pub money: Wallet,
    pub birth: GameTime,
    pub cur_age: GameTime,
    pub cur_quest: u16,
    pub quests: u8,
    pub claim_check: i64,
    pub play_tm: Time,
    pub name: String,
    pub race: Race,
    pub sex: Sex,
    pub class: Class,
    pub history: Vec<String>,
    pub cheated: u8,
    pub age: u16,
    pub ht: u16,
    pub wt: u16,
    pub sc: i16,
    pub max_exp: i64,
    pub exp: i64,
    pub rep: i64,
    pub lev: u16,
    pub max_lev: u16,
    pub expfact: libc::c_float,
    pub fos: i16,
    pub stl: i16,
    pub bth: i16,
    pub bthb: i16,
    pub mana: i16,
    pub cmana: libc::c_float,
    pub ptohit: i16,
    pub ptodam: i16,
    pub pac: i16,
    pub ptoac: i16,
    pub dis_th: i16,
    pub dis_td: i16,
    pub dis_ac: i16,
    pub dis_tac: i16,
    pub disarm: i16,
    pub save: i16,
    pub inven_weight: libc::c_long,
    pub flags: PlayerFlags,
    pub player: Player,
    pub char_row: libc::c_long,
    pub char_col: libc::c_long,
}
