use crate::model::{Class, Spell};

fn from_usize_for_adventurer(level: usize) -> Option<Spell> {
    match level {
        1 => Some(Spell {
            name: "Magic Missile",
            level: 3,
            mana: 1,
            fail: 30,
        }),
        2 => Some(Spell {
            name: "Detect Monsters",
            level: 3,
            mana: 2,
            fail: 35,
        }),
        3 => Some(Spell {
            name: "Phase Door",
            level: 3,
            mana: 2,
            fail: 35,
        }),
        4 => Some(Spell {
            name: "Light Area",
            level: 5,
            mana: 3,
            fail: 26,
        }),
        5 => Some(Spell {
            name: "Cure Light Wounds",
            level: 5,
            mana: 3,
            fail: 25,
        }),
        6 => Some(Spell {
            name: "Find Hidden Traps/Doors",
            level: 7,
            mana: 4,
            fail: 45,
        }),
        7 => Some(Spell {
            name: "Stinking Cloud",
            level: 7,
            mana: 6,
            fail: 40,
        }),
        8 => Some(Spell {
            name: "Confusion",
            level: 9,
            mana: 6,
            fail: 40,
        }),
        9 => Some(Spell {
            name: "Lightning Bolt",
            level: 9,
            mana: 7,
            fail: 40,
        }),
        10 => Some(Spell {
            name: "Trap/Door Destruction",
            level: 11,
            mana: 8,
            fail: 45,
        }),
        11 => Some(Spell {
            name: "Sleep I",
            level: 11,
            mana: 8,
            fail: 40,
        }),
        12 => Some(Spell {
            name: "Cure Poison",
            level: 13,
            mana: 9,
            fail: 45,
        }),
        13 => Some(Spell {
            name: "Shadow Door",
            level: 13,
            mana: 10,
            fail: 45,
        }),
        14 => Some(Spell {
            name: "Remove Curse",
            level: 15,
            mana: 11,
            fail: 55,
        }),
        15 => Some(Spell {
            name: "Frost Bolt",
            level: 15,
            mana: 12,
            fail: 50,
        }),
        16 => Some(Spell {
            name: "Create Food",
            level: 17,
            mana: 12,
            fail: 55,
        }),
        17 => Some(Spell {
            name: "Infravision",
            level: 17,
            mana: 12,
            fail: 50,
        }),
        18 => Some(Spell {
            name: "Invisibility",
            level: 17,
            mana: 13,
            fail: 50,
        }),
        19 => Some(Spell {
            name: "Turn Stone to Mud",
            level: 19,
            mana: 15,
            fail: 50,
        }),
        20 => Some(Spell {
            name: "Recharge Item I",
            level: 19,
            mana: 17,
            fail: 90,
        }),
        21 => Some(Spell {
            name: "Sleep II",
            level: 21,
            mana: 17,
            fail: 55,
        }),
        22 => Some(Spell {
            name: "Phantasmal Force",
            level: 21,
            mana: 19,
            fail: 50,
        }),
        23 => Some(Spell {
            name: "Polymorph Other",
            level: 23,
            mana: 19,
            fail: 60,
        }),
        24 => Some(Spell {
            name: "Identify",
            level: 23,
            mana: 25,
            fail: 95,
        }),
        25 => Some(Spell {
            name: "Ring of Frost",
            level: 25,
            mana: 19,
            fail: 60,
        }),
        26 => Some(Spell {
            name: "Sleep III",
            level: 25,
            mana: 20,
            fail: 60,
        }),
        27 => Some(Spell {
            name: "Hold Monster",
            level: 27,
            mana: 20,
            fail: 50,
        }),
        28 => Some(Spell {
            name: "Fire Bolt",
            level: 27,
            mana: 20,
            fail: 60,
        }),
        29 => Some(Spell {
            name: "Slow Creature",
            level: 29,
            mana: 21,
            fail: 65,
        }),
        30 => Some(Spell {
            name: "Protection From Magic",
            level: 31,
            mana: 21,
            fail: 70,
        }),
        31 => Some(Spell {
            name: "Frost Ball",
            level: 31,
            mana: 21,
            fail: 65,
        }),
        32 => Some(Spell {
            name: "Death Spell",
            level: 33,
            mana: 21,
            fail: 60,
        }),
        33 => Some(Spell {
            name: "Ring of Fire",
            level: 35,
            mana: 21,
            fail: 65,
        }),
        34 => Some(Spell {
            name: "Recharge Item II",
            level: 35,
            mana: 23,
            fail: 95,
        }),
        35 => Some(Spell {
            name: "Teleport Other",
            level: 37,
            mana: 25,
            fail: 70,
        }),
        36 => Some(Spell {
            name: "Haste Self",
            level: 37,
            mana: 25,
            fail: 75,
        }),
        37 => Some(Spell {
            name: "Fire Ball",
            level: 39,
            mana: 27,
            fail: 80,
        }),
        38 => Some(Spell {
            name: "Power Word: Destruction",
            level: 39,
            mana: 30,
            fail: 95,
        }),
        _ => None,
    }
}

fn from_usize_for_wizard(level: usize) -> Option<Spell> {
    match level {
        0 => Some(Spell {
            name: "Magic Missile",
            level: 1,
            mana: 1,
            fail: 22,
        }),
        1 => Some(Spell {
            name: "Detect Monsters",
            level: 1,
            mana: 1,
            fail: 23,
        }),
        2 => Some(Spell {
            name: "Phase Door",
            level: 1,
            mana: 2,
            fail: 24,
        }),
        3 => Some(Spell {
            name: "Light Area",
            level: 1,
            mana: 2,
            fail: 26,
        }),
        4 => Some(Spell {
            name: "Cure Light Wounds",
            level: 3,
            mana: 3,
            fail: 25,
        }),
        5 => Some(Spell {
            name: "Find Hidden Traps/Doors",
            level: 3,
            mana: 3,
            fail: 55,
        }),
        6 => Some(Spell {
            name: "Stinking Cloud",
            level: 3,
            mana: 4,
            fail: 27,
        }),
        7 => Some(Spell {
            name: "Confusion",
            level: 3,
            mana: 4,
            fail: 30,
        }),
        8 => Some(Spell {
            name: "Lightning Bolt",
            level: 5,
            mana: 4,
            fail: 30,
        }),
        9 => Some(Spell {
            name: "Trap/Door Destruction",
            level: 5,
            mana: 5,
            fail: 30,
        }),
        10 => Some(Spell {
            name: "Sleep I",
            level: 5,
            mana: 5,
            fail: 30,
        }),
        11 => Some(Spell {
            name: "Cure Poison",
            level: 5,
            mana: 5,
            fail: 35,
        }),
        12 => Some(Spell {
            name: "Shadow Door",
            level: 7,
            mana: 6,
            fail: 35,
        }),
        13 => Some(Spell {
            name: "Remove Curse",
            level: 7,
            mana: 6,
            fail: 50,
        }),
        14 => Some(Spell {
            name: "Frost Bolt",
            level: 7,
            mana: 6,
            fail: 40,
        }),
        15 => Some(Spell {
            name: "Create Food",
            level: 7,
            mana: 6,
            fail: 40,
        }),
        16 => Some(Spell {
            name: "Infravision",
            level: 7,
            mana: 6,
            fail: 40,
        }),
        17 => Some(Spell {
            name: "Invisibility",
            level: 7,
            mana: 6,
            fail: 35,
        }),
        18 => Some(Spell {
            name: "Turn Stone to Mud",
            level: 9,
            mana: 7,
            fail: 44,
        }),
        19 => Some(Spell {
            name: "Recharge Item I",
            level: 9,
            mana: 7,
            fail: 75,
        }),
        20 => Some(Spell {
            name: "Sleep II",
            level: 9,
            mana: 7,
            fail: 45,
        }),
        21 => Some(Spell {
            name: "Phantasmal Force",
            level: 11,
            mana: 7,
            fail: 50,
        }),
        22 => Some(Spell {
            name: "Polymorph Other",
            level: 11,
            mana: 7,
            fail: 45,
        }),
        23 => Some(Spell {
            name: "Identify",
            level: 11,
            mana: 7,
            fail: 99,
        }),
        24 => Some(Spell {
            name: "Ring of Frost",
            level: 13,
            mana: 7,
            fail: 45,
        }),
        25 => Some(Spell {
            name: "Sleep III",
            level: 13,
            mana: 7,
            fail: 50,
        }),
        26 => Some(Spell {
            name: "Hold Monster",
            level: 15,
            mana: 9,
            fail: 50,
        }),
        27 => Some(Spell {
            name: "Fire Bolt",
            level: 15,
            mana: 9,
            fail: 50,
        }),
        28 => Some(Spell {
            name: "Slow Creature",
            level: 17,
            mana: 9,
            fail: 50,
        }),
        29 => Some(Spell {
            name: "Protection from Magic",
            level: 17,
            mana: 9,
            fail: 55,
        }),
        30 => Some(Spell {
            name: "Frost Ball",
            level: 19,
            mana: 12,
            fail: 55,
        }),
        31 => Some(Spell {
            name: "Death Spell",
            level: 19,
            mana: 18,
            fail: 55,
        }),
        32 => Some(Spell {
            name: "Ring of Fire",
            level: 21,
            mana: 12,
            fail: 60,
        }),
        33 => Some(Spell {
            name: "Recharge Item II",
            level: 21,
            mana: 12,
            fail: 90,
        }),
        34 => Some(Spell {
            name: "Teleport Other",
            level: 23,
            mana: 15,
            fail: 60,
        }),
        35 => Some(Spell {
            name: "Haste Self",
            level: 25,
            mana: 15,
            fail: 65,
        }),
        36 => Some(Spell {
            name: "Fire Ball",
            level: 28,
            mana: 18,
            fail: 65,
        }),
        37 => Some(Spell {
            name: "Power Word: Destruction",
            level: 31,
            mana: 21,
            fail: 80,
        }),
        38 => Some(Spell {
            name: "Power Word: Kill",
            level: 34,
            mana: 25,
            fail: 80,
        }),
        39 => Some(Spell {
            name: "Genocide",
            level: 37,
            mana: 25,
            fail: 95,
        }),
        _ => None,
    }
}

fn from_usize_for_cleric(level: usize) -> Option<Spell> {
    match level {
        0 => Some(Spell {
            name: "Detect Evil",
            level: 1,
            mana: 1,
            fail: 10,
        }),
        1 => Some(Spell {
            name: "Cure Light Wounds",
            level: 1,
            mana: 2,
            fail: 15,
        }),
        2 => Some(Spell {
            name: "Bless",
            level: 1,
            mana: 2,
            fail: 20,
        }),
        3 => Some(Spell {
            name: "Remove Fear",
            level: 1,
            mana: 2,
            fail: 25,
        }),
        4 => Some(Spell {
            name: "Call Light",
            level: 3,
            mana: 2,
            fail: 25,
        }),
        5 => Some(Spell {
            name: "Find Traps",
            level: 3,
            mana: 3,
            fail: 27,
        }),
        6 => Some(Spell {
            name: "Detect Doors/Stairs",
            level: 3,
            mana: 3,
            fail: 27,
        }),
        7 => Some(Spell {
            name: "Slow Poison",
            level: 3,
            mana: 3,
            fail: 28,
        }),
        8 => Some(Spell {
            name: "Blind Creature",
            level: 5,
            mana: 4,
            fail: 29,
        }),
        9 => Some(Spell {
            name: "Portal",
            level: 5,
            mana: 4,
            fail: 30,
        }),
        10 => Some(Spell {
            name: "Cure Medium Wounds",
            level: 5,
            mana: 4,
            fail: 32,
        }),
        11 => Some(Spell {
            name: "Ray of Sanctification",
            level: 5,
            mana: 4,
            fail: 40,
        }),
        12 => Some(Spell {
            name: "Heroism",
            level: 7,
            mana: 4,
            fail: 40,
        }),
        13 => Some(Spell {
            name: "Sanctuary",
            level: 7,
            mana: 5,
            fail: 36,
        }),
        14 => Some(Spell {
            name: "Remove Curse",
            level: 7,
            mana: 6,
            fail: 38,
        }),
        15 => Some(Spell {
            name: "Resist Heat and Cold",
            level: 7,
            mana: 7,
            fail: 38,
        }),
        16 => Some(Spell {
            name: "Silence",
            level: 9,
            mana: 7,
            fail: 40,
        }),
        17 => Some(Spell {
            name: "Resist Petrification",
            level: 9,
            mana: 7,
            fail: 40,
        }),
        18 => Some(Spell {
            name: "Neutralize Poison",
            level: 9,
            mana: 7,
            fail: 38,
        }),
        19 => Some(Spell {
            name: "Cure Serious Wounds",
            level: 9,
            mana: 7,
            fail: 40,
        }),
        20 => Some(Spell {
            name: "Chant",
            level: 11,
            mana: 8,
            fail: 34,
        }),
        21 => Some(Spell {
            name: "Sense Invisible",
            level: 11,
            mana: 8,
            fail: 42,
        }),
        22 => Some(Spell {
            name: "Protection from Evil",
            level: 11,
            mana: 8,
            fail: 42,
        }),
        23 => Some(Spell {
            name: "Earthquake",
            level: 11,
            mana: 9,
            fail: 55,
        }),
        24 => Some(Spell {
            name: "Create Food and Drink",
            level: 13,
            mana: 9,
            fail: 38,
        }),
        25 => Some(Spell {
            name: "Sense Surroundings",
            level: 13,
            mana: 10,
            fail: 45,
        }),
        26 => Some(Spell {
            name: "Orb of Draining",
            level: 13,
            mana: 10,
            fail: 58,
        }),
        27 => Some(Spell {
            name: "Cure Critical Wounds",
            level: 15,
            mana: 11,
            fail: 45,
        }),
        28 => Some(Spell {
            name: "Turn Undead",
            level: 15,
            mana: 12,
            fail: 50,
        }),
        29 => Some(Spell {
            name: "Holy Prayer",
            level: 17,
            mana: 14,
            fail: 50,
        }),
        30 => Some(Spell {
            name: "Dispel Undead",
            level: 17,
            mana: 14,
            fail: 55,
        }),
        31 => Some(Spell {
            name: "Resist Paralysis",
            level: 19,
            mana: 15,
            fail: 55,
        }),
        32 => Some(Spell {
            name: "Blade Barrier",
            level: 21,
            mana: 16,
            fail: 60,
        }),
        33 => Some(Spell {
            name: "Dispel Evil",
            level: 23,
            mana: 18,
            fail: 70,
        }),
        34 => Some(Spell {
            name: "Heal",
            level: 25,
            mana: 20,
            fail: 60,
        }),
        35 => Some(Spell {
            name: "Resist Magic",
            level: 27,
            mana: 22,
            fail: 80,
        }),
        36 => Some(Spell {
            name: "Holy of Thunder",
            level: 30,
            mana: 23,
            fail: 70,
        }),
        37 => Some(Spell {
            name: "Glyph of Warding",
            level: 33,
            mana: 24,
            fail: 90,
        }),
        38 => Some(Spell {
            name: "Hero's Feast",
            level: 35,
            mana: 28,
            fail: 95,
        }),
        39 => Some(Spell {
            name: "Holy Word",
            level: 39,
            mana: 32,
            fail: 99,
        }),
        _ => None,
    }
}

fn from_usize_for_rogue(level: usize) -> Option<Spell> {
    match level {
        0 => Some(Spell {
            name: "Detect Monsters",
            level: 3,
            mana: 2,
            fail: 35,
        }),
        1 => Some(Spell {
            name: "Battle Song",
            level: 3,
            mana: 2,
            fail: 35,
        }),
        2 => Some(Spell {
            name: "Blink",
            level: 3,
            mana: 2,
            fail: 35,
        }),
        3 => Some(Spell {
            name: "Light Area",
            level: 5,
            mana: 4,
            fail: 35,
        }),
        4 => Some(Spell {
            name: "Find Hidden Doors/Traps",
            level: 5,
            mana: 5,
            fail: 45,
        }),
        5 => Some(Spell {
            name: "Magical Jig",
            level: 7,
            mana: 8,
            fail: 40,
        }),
        6 => Some(Spell {
            name: "Detect Magic",
            level: 7,
            mana: 9,
            fail: 70,
        }),
        8 => Some(Spell {
            name: "Battle Dance",
            level: 9,
            mana: 10,
            fail: 45,
        }),
        9 => Some(Spell {
            name: "Charm Monsters",
            level: 9,
            mana: 11,
            fail: 50,
        }),
        10 => Some(Spell {
            name: "Detect Curse",
            level: 11,
            mana: 12,
            fail: 40,
        }),
        11 => Some(Spell {
            name: "Detect Invisible",
            level: 11,
            mana: 12,
            fail: 40,
        }),
        12 => Some(Spell {
            name: "Cure Poison",
            level: 13,
            mana: 14,
            fail: 45,
        }),
        13 => Some(Spell {
            name: "Invisibility",
            level: 15,
            mana: 16,
            fail: 50,
        }),
        14 => Some(Spell {
            name: "Shadow Gate",
            level: 17,
            mana: 18,
            fail: 55,
        }),
        17 => Some(Spell {
            name: "Recharge Item",
            level: 19,
            mana: 18,
            fail: 55,
        }),
        18 => Some(Spell {
            name: "Remove Curse",
            level: 21,
            mana: 20,
            fail: 90,
        }),
        19 => Some(Spell {
            name: "Legend Lore",
            level: 23,
            mana: 22,
            fail: 95,
        }),
        21 => Some(Spell {
            name: "Detect Treasure",
            level: 25,
            mana: 25,
            fail: 50,
        }),
        22 => Some(Spell {
            name: "Detect Object",
            level: 25,
            mana: 25,
            fail: 55,
        }),
        26 => Some(Spell {
            name: "Word of Recall",
            level: 27,
            mana: 27,
            fail: 60,
        }),
        28 => Some(Spell {
            name: "See Invisible",
            level: 29,
            mana: 29,
            fail: 65,
        }),
        29 => Some(Spell {
            name: "Magic Mapping",
            level: 31,
            mana: 30,
            fail: 70,
        }),
        31 => Some(Spell {
            name: "Battle Frenzy",
            level: 33,
            mana: 31,
            fail: 70,
        }),
        33 => Some(Spell {
            name: "Resist Charm",
            level: 35,
            mana: 32,
            fail: 70,
        }),
        34 => Some(Spell {
            name: "Item Lore",
            level: 37,
            mana: 33,
            fail: 95,
        }),
        _ => None,
    }
}

fn from_usize_for_ranger(level: usize) -> Option<Spell> {
    match level {
        0 => Some(Spell {
            name: "Moon Beam",
            level: 1,
            mana: 2,
            fail: 20,
        }),
        1 => Some(Spell {
            name: "Detect Monster",
            level: 1,
            mana: 2,
            fail: 33,
        }),
        2 => Some(Spell {
            name: "Battle Song",
            level: 2,
            mana: 3,
            fail: 35,
        }),
        3 => Some(Spell {
            name: "Light",
            level: 2,
            mana: 3,
            fail: 35,
        }),
        4 => Some(Spell {
            name: "Minor Cure",
            level: 3,
            mana: 4,
            fail: 40,
        }),
        5 => Some(Spell {
            name: "Find Safe Path",
            level: 4,
            mana: 5,
            fail: 45,
        }),
        6 => Some(Spell {
            name: "Magical Jig",
            level: 4,
            mana: 5,
            fail: 45,
        }),
        7 => Some(Spell {
            name: "Warp Wood",
            level: 4,
            mana: 5,
            fail: 45,
        }),
        8 => Some(Spell {
            name: "Battle Dance",
            level: 5,
            mana: 5,
            fail: 40,
        }),
        9 => Some(Spell {
            name: "Cure Poison",
            level: 5,
            mana: 5,
            fail: 48,
        }),
        10 => Some(Spell {
            name: "Charm",
            level: 7,
            mana: 5,
            fail: 35,
        }),
        11 => Some(Spell {
            name: "Detect Curse",
            level: 7,
            mana: 6,
            fail: 45,
        }),
        12 => Some(Spell {
            name: "Summon Insects",
            level: 7,
            mana: 7,
            fail: 50,
        }),
        13 => Some(Spell {
            name: "Call Lightning",
            level: 9,
            mana: 9,
            fail: 55,
        }),
        14 => Some(Spell {
            name: "Magic Resistance",
            level: 9,
            mana: 10,
            fail: 45,
        }),
        16 => Some(Spell {
            name: "Create Food",
            level: 9,
            mana: 10,
            fail: 55,
        }),
        17 => Some(Spell {
            name: "Remove Curse",
            level: 11,
            mana: 10,
            fail: 45,
        }),
        18 => Some(Spell {
            name: "Infravision",
            level: 11,
            mana: 10,
            fail: 50,
        }),
        19 => Some(Spell {
            name: "Major Cure",
            level: 11,
            mana: 11,
            fail: 50,
        }),
        20 => Some(Spell {
            name: "Resist Petrification",
            level: 13,
            mana: 11,
            fail: 55,
        }),
        21 => Some(Spell {
            name: "Transplant",
            level: 13,
            mana: 11,
            fail: 45,
        }),
        23 => Some(Spell {
            name: "Dispel Magic",
            level: 15,
            mana: 11,
            fail: 58,
        }),
        24 => Some(Spell {
            name: "Fire Stream",
            level: 15,
            mana: 11,
            fail: 70,
        }),
        25 => Some(Spell {
            name: "Protection from Nature",
            level: 17,
            mana: 12,
            fail: 55,
        }),
        26 => Some(Spell {
            name: "Stone to Mud",
            level: 17,
            mana: 12,
            fail: 55,
        }),
        27 => Some(Spell {
            name: "Goodberry",
            level: 19,
            mana: 14,
            fail: 65,
        }),
        28 => Some(Spell {
            name: "Creeping Doom",
            level: 37,
            mana: 21,
            fail: 65,
        }),
        29 => Some(Spell {
            name: "Pillar of Fire",
            level: 23,
            mana: 15,
            fail: 65,
        }),
        30 => Some(Spell {
            name: "Word of Recall",
            level: 25,
            mana: 15,
            fail: 50,
        }),
        31 => Some(Spell {
            name: "Lightning Ball",
            level: 27,
            mana: 15,
            fail: 90,
        }),
        32 => Some(Spell {
            name: "Word of Blindness",
            level: 29,
            mana: 16,
            fail: 55,
        }),
        33 => Some(Spell {
            name: "Protection from Monsters",
            level: 31,
            mana: 20,
            fail: 60,
        }),
        36 => Some(Spell {
            name: "Resist Charm",
            level: 33,
            mana: 22,
            fail: 65,
        }),
        37 => Some(Spell {
            name: "Battle Frenzy",
            level: 35,
            mana: 25,
            fail: 65,
        }),
        38 => Some(Spell {
            name: "Dispel Monster",
            level: 37,
            mana: 30,
            fail: 70,
        }),
        _ => None,
    }
}

fn from_usize_for_paladin(level: usize) -> Option<Spell> {
    match level {
        0 => Some(Spell {
            name: "Detect Evil",
            level: 1,
            mana: 1,
            fail: 30,
        }),
        1 => Some(Spell {
            name: "Cure Light Wounds",
            level: 2,
            mana: 2,
            fail: 35,
        }),
        2 => Some(Spell {
            name: "Bless",
            level: 3,
            mana: 3,
            fail: 35,
        }),
        3 => Some(Spell {
            name: "Remove Fear",
            level: 5,
            mana: 3,
            fail: 35,
        }),
        4 => Some(Spell {
            name: "Call Light",
            level: 5,
            mana: 4,
            fail: 35,
        }),
        5 => Some(Spell {
            name: "Find Traps",
            level: 7,
            mana: 5,
            fail: 40,
        }),
        6 => Some(Spell {
            name: "Detect Doors/Stairs",
            level: 7,
            mana: 5,
            fail: 40,
        }),
        7 => Some(Spell {
            name: "Slow Poison",
            level: 9,
            mana: 7,
            fail: 40,
        }),
        8 => Some(Spell {
            name: "Blind Creature",
            level: 9,
            mana: 7,
            fail: 40,
        }),
        9 => Some(Spell {
            name: "Portal",
            level: 9,
            mana: 8,
            fail: 40,
        }),
        10 => Some(Spell {
            name: "Cure Medium Wounds",
            level: 11,
            mana: 9,
            fail: 40,
        }),
        11 => Some(Spell {
            name: "Ray of Sanctification",
            level: 11,
            mana: 9,
            fail: 40,
        }),
        12 => Some(Spell {
            name: "Heroism",
            level: 11,
            mana: 9,
            fail: 40,
        }),
        13 => Some(Spell {
            name: "Sanctuary",
            level: 13,
            mana: 10,
            fail: 45,
        }),
        14 => Some(Spell {
            name: "Remove Curse",
            level: 13,
            mana: 11,
            fail: 45,
        }),
        15 => Some(Spell {
            name: "Resist Heat and Cold",
            level: 15,
            mana: 13,
            fail: 45,
        }),
        16 => Some(Spell {
            name: "Silence",
            level: 15,
            mana: 13,
            fail: 45,
        }),
        17 => Some(Spell {
            name: "Resist Petrification",
            level: 15,
            mana: 13,
            fail: 50,
        }),
        18 => Some(Spell {
            name: "Neutralize Poison",
            level: 15,
            mana: 15,
            fail: 50,
        }),
        19 => Some(Spell {
            name: "Cure Serious Wounds",
            level: 17,
            mana: 15,
            fail: 50,
        }),
        20 => Some(Spell {
            name: "Chant",
            level: 17,
            mana: 15,
            fail: 70,
        }),
        21 => Some(Spell {
            name: "Sense Invisible",
            level: 19,
            mana: 15,
            fail: 50,
        }),
        22 => Some(Spell {
            name: "Protection from Evil",
            level: 19,
            mana: 15,
            fail: 50,
        }),
        23 => Some(Spell {
            name: "Earthquake",
            level: 21,
            mana: 17,
            fail: 50,
        }),
        24 => Some(Spell {
            name: "Create Food and Drink",
            level: 21,
            mana: 10,
            fail: 45,
        }),
        25 => Some(Spell {
            name: "Sense Surroundings",
            level: 23,
            mana: 17,
            fail: 50,
        }),
        26 => Some(Spell {
            name: "Orb of Draining",
            level: 23,
            mana: 20,
            fail: 85,
        }),
        27 => Some(Spell {
            name: "Cure Critical Wounds",
            level: 25,
            mana: 20,
            fail: 50,
        }),
        28 => Some(Spell {
            name: "Turn Undead",
            level: 25,
            mana: 21,
            fail: 50,
        }),
        29 => Some(Spell {
            name: "Holy Prayer",
            level: 27,
            mana: 22,
            fail: 50,
        }),
        30 => Some(Spell {
            name: "Dispel Undead",
            level: 29,
            mana: 24,
            fail: 60,
        }),
        31 => Some(Spell {
            name: "Resist Paralysis",
            level: 31,
            mana: 26,
            fail: 55,
        }),
        32 => Some(Spell {
            name: "Blade Barrier",
            level: 33,
            mana: 27,
            fail: 60,
        }),
        33 => Some(Spell {
            name: "Dispel Evil",
            level: 35,
            mana: 28,
            fail: 70,
        }),
        34 => Some(Spell {
            name: "Heal",
            level: 37,
            mana: 32,
            fail: 75,
        }),
        35 => Some(Spell {
            name: "Resist Magic",
            level: 38,
            mana: 32,
            fail: 75,
        }),
        36 => Some(Spell {
            name: "Holy Thunder",
            level: 39,
            mana: 30,
            fail: 80,
        }),
        _ => None,
    }
}

fn from_usize_for_druid(level: usize) -> Option<Spell> {
    match level {
        0 => Some(Spell {
            name: "Moon Beam",
            level: 1,
            mana: 1,
            fail: 15,
        }),
        1 => Some(Spell {
            name: "Detect Monster",
            level: 1,
            mana: 1,
            fail: 15,
        }),
        2 => Some(Spell {
            name: "Battle Song",
            level: 1,
            mana: 2,
            fail: 20,
        }),
        3 => Some(Spell {
            name: "Light",
            level: 1,
            mana: 2,
            fail: 25,
        }),
        4 => Some(Spell {
            name: "Minor Cure",
            level: 3,
            mana: 3,
            fail: 25,
        }),
        5 => Some(Spell {
            name: "Find Safe Path",
            level: 3,
            mana: 3,
            fail: 28,
        }),
        6 => Some(Spell {
            name: "Magical Jig",
            level: 3,
            mana: 3,
            fail: 27,
        }),
        7 => Some(Spell {
            name: "Warp Wood",
            level: 3,
            mana: 4,
            fail: 29,
        }),
        8 => Some(Spell {
            name: "Battle Dance",
            level: 5,
            mana: 4,
            fail: 30,
        }),
        9 => Some(Spell {
            name: "Cure Poison",
            level: 5,
            mana: 4,
            fail: 30,
        }),
        10 => Some(Spell {
            name: "Charm",
            level: 5,
            mana: 5,
            fail: 45,
        }),
        11 => Some(Spell {
            name: "Detect Curse",
            level: 5,
            mana: 5,
            fail: 50,
        }),
        12 => Some(Spell {
            name: "Summon Insects",
            level: 7,
            mana: 5,
            fail: 35,
        }),
        13 => Some(Spell {
            name: "Call Lightning",
            level: 7,
            mana: 5,
            fail: 38,
        }),
        14 => Some(Spell {
            name: "Magic Resistance",
            level: 7,
            mana: 6,
            fail: 40,
        }),
        15 => Some(Spell {
            name: "Starlight",
            level: 7,
            mana: 6,
            fail: 40,
        }),
        16 => Some(Spell {
            name: "Create Food",
            level: 9,
            mana: 6,
            fail: 40,
        }),
        17 => Some(Spell {
            name: "Remove Curse",
            level: 9,
            mana: 6,
            fail: 55,
        }),
        18 => Some(Spell {
            name: "Infravision",
            level: 9,
            mana: 7,
            fail: 40,
        }),
        19 => Some(Spell {
            name: "Major Cure",
            level: 9,
            mana: 7,
            fail: 40,
        }),
        20 => Some(Spell {
            name: "Resist Petrification",
            level: 11,
            mana: 7,
            fail: 45,
        }),
        21 => Some(Spell {
            name: "Transplant",
            level: 11,
            mana: 8,
            fail: 55,
        }),
        22 => Some(Spell {
            name: "Sunray",
            level: 11,
            mana: 9,
            fail: 60,
        }),
        23 => Some(Spell {
            name: "Dispel Magic",
            level: 11,
            mana: 9,
            fail: 50,
        }),
        24 => Some(Spell {
            name: "Fire Stream",
            level: 11,
            mana: 9,
            fail: 65,
        }),
        25 => Some(Spell {
            name: "Protection from Nature",
            level: 13,
            mana: 9,
            fail: 40,
        }),
        26 => Some(Spell {
            name: "Stone to Mud",
            level: 13,
            mana: 9,
            fail: 50,
        }),
        27 => Some(Spell {
            name: "Goodberry",
            level: 15,
            mana: 11,
            fail: 50,
        }),
        28 => Some(Spell {
            name: "Creeping Doom",
            level: 33,
            mana: 17,
            fail: 65,
        }),
        29 => Some(Spell {
            name: "Pillar of Fire",
            level: 15,
            mana: 11,
            fail: 55,
        }),
        30 => Some(Spell {
            name: "Word of Recall",
            level: 17,
            mana: 11,
            fail: 60,
        }),
        31 => Some(Spell {
            name: "Lightning Ball",
            level: 17,
            mana: 12,
            fail: 55,
        }),
        32 => Some(Spell {
            name: "Word of Blindness",
            level: 19,
            mana: 12,
            fail: 55,
        }),
        33 => Some(Spell {
            name: "Protection from Monsters",
            level: 21,
            mana: 14,
            fail: 55,
        }),
        34 => Some(Spell {
            name: "Control Temperature",
            level: 23,
            mana: 17,
            fail: 60,
        }),
        35 => Some(Spell {
            name: "Ring of Fire",
            level: 25,
            mana: 19,
            fail: 75,
        }),
        36 => Some(Spell {
            name: "Resist Charm",
            level: 27,
            mana: 21,
            fail: 75,
        }),
        37 => Some(Spell {
            name: "Battle Frenzy",
            level: 29,
            mana: 23,
            fail: 70,
        }),
        38 => Some(Spell {
            name: "Dispel Monster",
            level: 31,
            mana: 25,
            fail: 80,
        }),
        39 => Some(Spell {
            name: "Note of Destruction",
            level: 34,
            mana: 27,
            fail: 85,
        }),
        _ => None,
    }
}

fn from_usize_for_bard(level: usize) -> Option<Spell> {
    match level {
        0 => Some(Spell {
            name: "Detect Monsters",
            level: 1,
            mana: 1,
            fail: 35,
        }),
        1 => Some(Spell {
            name: "Battle Song",
            level: 1,
            mana: 2,
            fail: 35,
        }),
        2 => Some(Spell {
            name: "Blink",
            level: 1,
            mana: 2,
            fail: 35,
        }),
        3 => Some(Spell {
            name: "Light Area",
            level: 1,
            mana: 2,
            fail: 35,
        }),
        4 => Some(Spell {
            name: "Detect Hidden Doors/Traps",
            level: 3,
            mana: 3,
            fail: 45,
        }),
        5 => Some(Spell {
            name: "Magical Jig",
            level: 3,
            mana: 4,
            fail: 40,
        }),
        6 => Some(Spell {
            name: "Detect Magic",
            level: 3,
            mana: 4,
            fail: 60,
        }),
        7 => Some(Spell {
            name: "Minor Cure",
            level: 3,
            mana: 4,
            fail: 40,
        }),
        8 => Some(Spell {
            name: "Battle Dance",
            level: 5,
            mana: 5,
            fail: 45,
        }),
        9 => Some(Spell {
            name: "Charm Monsters",
            level: 5,
            mana: 5,
            fail: 40,
        }),
        10 => Some(Spell {
            name: "Detect Curse",
            level: 5,
            mana: 9,
            fail: 50,
        }),
        11 => Some(Spell {
            name: "Detect Invisible",
            level: 7,
            mana: 8,
            fail: 45,
        }),
        12 => Some(Spell {
            name: "Cure Poison",
            level: 7,
            mana: 8,
            fail: 45,
        }),
        13 => Some(Spell {
            name: "Invisibility",
            level: 7,
            mana: 11,
            fail: 55,
        }),
        14 => Some(Spell {
            name: "Teleport Self",
            level: 9,
            mana: 10,
            fail: 50,
        }),
        15 => Some(Spell {
            name: "Infravision",
            level: 9,
            mana: 11,
            fail: 55,
        }),
        16 => Some(Spell {
            name: "Physical Humor",
            level: 9,
            mana: 11,
            fail: 55,
        }),
        17 => Some(Spell {
            name: "Recharge Item",
            level: 11,
            mana: 11,
            fail: 85,
        }),
        18 => Some(Spell {
            name: "Remove Curse",
            level: 13,
            mana: 12,
            fail: 55,
        }),
        19 => Some(Spell {
            name: "Legend Lore",
            level: 11,
            mana: 13,
            fail: 99,
        }),
        20 => Some(Spell {
            name: "Mass Charm",
            level: 11,
            mana: 12,
            fail: 55,
        }),
        21 => Some(Spell {
            name: "Detect Treasure",
            level: 13,
            mana: 11,
            fail: 80,
        }),
        22 => Some(Spell {
            name: "Detect Object",
            level: 13,
            mana: 11,
            fail: 80,
        }),
        23 => Some(Spell {
            name: "Resist Petrification",
            level: 15,
            mana: 12,
            fail: 60,
        }),
        24 => Some(Spell {
            name: "Create Food and Drink",
            level: 15,
            mana: 13,
            fail: 60,
        }),
        25 => Some(Spell {
            name: "Panic",
            level: 15,
            mana: 15,
            fail: 60,
        }),
        26 => Some(Spell {
            name: "Word of Recall",
            level: 17,
            mana: 15,
            fail: 60,
        }),
        27 => Some(Spell {
            name: "Protection from Nature",
            level: 17,
            mana: 16,
            fail: 65,
        }),
        28 => Some(Spell {
            name: "See Invisible",
            level: 17,
            mana: 16,
            fail: 60,
        }),
        29 => Some(Spell {
            name: "Magic Mapping",
            level: 19,
            mana: 18,
            fail: 65,
        }),
        30 => Some(Spell {
            name: "Joke of Death",
            level: 19,
            mana: 18,
            fail: 60,
        }),
        31 => Some(Spell {
            name: "Battle Frenzy",
            level: 19,
            mana: 18,
            fail: 80,
        }),
        32 => Some(Spell {
            name: "Slow Creature",
            level: 21,
            mana: 19,
            fail: 65,
        }),
        33 => Some(Spell {
            name: "Resist Charm",
            level: 23,
            mana: 22,
            fail: 65,
        }),
        34 => Some(Spell {
            name: "Item Lore",
            level: 25,
            mana: 20,
            fail: 90,
        }),
        35 => Some(Spell {
            name: "Song of Protection",
            level: 27,
            mana: 25,
            fail: 70,
        }),
        36 => Some(Spell {
            name: "Last Laugh",
            level: 29,
            mana: 23,
            fail: 70,
        }),
        37 => Some(Spell {
            name: "Teleport Level",
            level: 31,
            mana: 27,
            fail: 75,
        }),
        38 => Some(Spell {
            name: "Clairvoyance",
            level: 35,
            mana: 29,
            fail: 92,
        }),
        39 => Some(Spell {
            name: "Song of Power",
            level: 39,
            mana: 32,
            fail: 97,
        }),
        _ => None,
    }
}

fn from_usize_for_monk(level: usize) -> Option<Spell> {
    match level {
        0 => Some(Spell {
            name: "Self-Healing",
            level: 3,
            mana: 3,
            fail: 50,
        }),
        1 => Some(Spell {
            name: "Courage",
            level: 5,
            mana: 5,
            fail: 50,
        }),
        2 => Some(Spell {
            name: "Slow Poison",
            level: 7,
            mana: 7,
            fail: 50,
        }),
        3 => Some(Spell {
            name: "Negate Hunger",
            level: 9,
            mana: 9,
            fail: 50,
        }),
        4 => Some(Spell {
            name: "Sense Enemies",
            level: 11,
            mana: 11,
            fail: 50,
        }),
        5 => Some(Spell {
            name: "Self-Healing II",
            level: 13,
            mana: 13,
            fail: 50,
        }),
        6 => Some(Spell {
            name: "Night Vision",
            level: 15,
            mana: 15,
            fail: 50,
        }),
        7 => Some(Spell {
            name: "Poison Immunity",
            level: 17,
            mana: 17,
            fail: 50,
        }),
        8 => Some(Spell {
            name: "See Invisible",
            level: 19,
            mana: 19,
            fail: 50,
        }),
        9 => Some(Spell {
            name: "Advanced Self-Healing",
            level: 21,
            mana: 21,
            fail: 50,
        }),
        10 => Some(Spell {
            name: "Resist Petrification",
            level: 23,
            mana: 23,
            fail: 50,
        }),
        11 => Some(Spell {
            name: "Stealth",
            level: 25,
            mana: 25,
            fail: 50,
        }),
        12 => Some(Spell {
            name: "Free Action",
            level: 27,
            mana: 27,
            fail: 50,
        }),
        13 => Some(Spell {
            name: "Improved Speed",
            level: 29,
            mana: 29,
            fail: 50,
        }),
        _ => None,
    }
}

pub fn from_usize(class: Class, level: usize) -> Option<Spell> {
    match class {
        Class::Adventurer => from_usize_for_adventurer(level),
        Class::Fighter => None,
        Class::Wizard => from_usize_for_wizard(level),
        Class::Cleric => from_usize_for_cleric(level),
        Class::Rogue => from_usize_for_rogue(level),
        Class::Ranger => from_usize_for_ranger(level),
        Class::Paladin => from_usize_for_paladin(level),
        Class::Druid => from_usize_for_druid(level),
        Class::Bard => from_usize_for_bard(level),
        Class::Monk => from_usize_for_monk(level),
        Class::Barbarian => None,
    }
}

pub fn from_usize_or_blank(class: Class, level: usize) -> Spell {
    from_usize(class, level).unwrap_or(Spell {
        name: "",
        level: 99,
        mana: 99,
        fail: 0,
    })
}
