use misc;
use model;

#[derive(Copy, Clone, Eq, PartialEq, Hash)]
pub enum PotionTemplate {
    AppleJuice,
    Blindness,
    Boldliness,
    Charisma,
    Confusion,
    CureCriticalWounds,
    CureLightWounds,
    CureSeriousWounds,
    DetectInvisible,
    FleaBile,
    GainConstitution,
    GainDexterity,
    GainExperience,
    GainIntelligence,
    GainStrength,
    GainWisdom,
    HasteSelf,
    Healing,
    Heroism,
    InfraVision,
    Invulnerability,
    Learning,
    LoseIntelligence,
    LoseMemories,
    LoseWisdom,
    NeutralizePoison,
    Poison,
    ResistCold,
    ResistHeat,
    RestoreCharisma,
    RestoreConstitution,
    RestoreDexterity,
    RestoreIntelligence,
    RestoreLifeLevels,
    RestoreMana,
    RestoreStrength,
    RestoreWisdom,
    SaltWater,
    Sleep,
    SlimeMoldJuice,
    SlowPoison,
    Slowness,
    SuperHeroism,
    Ugliness,
    Water,
}

impl PotionTemplate {
    pub fn iter() -> impl Iterator<Item=PotionTemplate> {
        [
            PotionTemplate::AppleJuice,
            PotionTemplate::Blindness,
            PotionTemplate::Boldliness,
            PotionTemplate::Charisma,
            PotionTemplate::Confusion,
            PotionTemplate::CureCriticalWounds,
            PotionTemplate::CureLightWounds,
            PotionTemplate::CureSeriousWounds,
            PotionTemplate::DetectInvisible,
            PotionTemplate::FleaBile,
            PotionTemplate::GainConstitution,
            PotionTemplate::GainDexterity,
            PotionTemplate::GainExperience,
            PotionTemplate::GainIntelligence,
            PotionTemplate::GainStrength,
            PotionTemplate::GainWisdom,
            PotionTemplate::HasteSelf,
            PotionTemplate::Healing,
            PotionTemplate::Heroism,
            PotionTemplate::InfraVision,
            PotionTemplate::Invulnerability,
            PotionTemplate::Learning,
            PotionTemplate::LoseIntelligence,
            PotionTemplate::LoseMemories,
            PotionTemplate::LoseWisdom,
            PotionTemplate::NeutralizePoison,
            PotionTemplate::Poison,
            PotionTemplate::ResistCold,
            PotionTemplate::ResistHeat,
            PotionTemplate::RestoreCharisma,
            PotionTemplate::RestoreConstitution,
            PotionTemplate::RestoreDexterity,
            PotionTemplate::RestoreIntelligence,
            PotionTemplate::RestoreLifeLevels,
            PotionTemplate::RestoreMana,
            PotionTemplate::RestoreStrength,
            PotionTemplate::RestoreWisdom,
            PotionTemplate::SaltWater,
            PotionTemplate::Sleep,
            PotionTemplate::SlimeMoldJuice,
            PotionTemplate::SlowPoison,
            PotionTemplate::Slowness,
            PotionTemplate::SuperHeroism,
            PotionTemplate::Ugliness,
            PotionTemplate::Water,
        ].iter().copied()
    }

    pub fn create(&self) -> model::Item {
        model::Item {
            name: self.name(),
            tval: model::ItemType::Potion1 as u8,
            flags: self.flags1(),
            flags2: self.flags2(),
            p1: self.p1(),
            cost: self.cost() * model::Currency::Gold.value(),
            subval: self.subval(),
            weight: 4,
            number: 1,
            tohit: 0,
            todam: 0,
            ac: 0,
            toac: 0,
            damage: misc::rs2item_damage("1d1"),
            level: 0,
            identified: 0,
        }
    }

    fn name(&self) -> model::Name {
        match self {
            PotionTemplate::AppleJuice => misc::rs2item_name("& %C Potion~| of Apple Juice"),
            PotionTemplate::Blindness => misc::rs2item_name("& %C Potion~| of Blindness"),
            PotionTemplate::Boldliness => misc::rs2item_name("& %C Potion~| of Boldliness"),
            PotionTemplate::Charisma => misc::rs2item_name("& %C Potion~| of Charisma"),
            PotionTemplate::Confusion => misc::rs2item_name("& %C Potion~| of Confusion"),
            PotionTemplate::CureCriticalWounds => misc::rs2item_name("& %C Potion~| of Cure Critical Wounds"),
            PotionTemplate::CureLightWounds => misc::rs2item_name("& %C Potion~| of Cure Light Wounds"),
            PotionTemplate::CureSeriousWounds => misc::rs2item_name("& %C Potion~| of Cure Serious Wounds"),
            PotionTemplate::DetectInvisible => misc::rs2item_name("& %C Potion~| of Detect Invisible"),
            PotionTemplate::FleaBile => misc::rs2item_name("& %C Potion~| of Flea Bile"),
            PotionTemplate::GainConstitution => misc::rs2item_name("& %C Potion~| of Gain Constitution"),
            PotionTemplate::GainDexterity => misc::rs2item_name("& %C Potion~| of Gain Dexterity"),
            PotionTemplate::GainExperience => misc::rs2item_name("& %C Potion~| of Gain Experience"),
            PotionTemplate::GainIntelligence => misc::rs2item_name("& %C Potion~| of Restore Strength"),
            PotionTemplate::GainStrength => misc::rs2item_name("& %C Potion~| of Gain Strength"),
            PotionTemplate::GainWisdom => misc::rs2item_name("& %C Potion~| of Gain Wisdom"),
            PotionTemplate::HasteSelf => misc::rs2item_name("& %C Potion~| of Haste Self"),
            PotionTemplate::Healing => misc::rs2item_name("& %C Potion~| of Healing"),
            PotionTemplate::Heroism => misc::rs2item_name("& %C Potion~| of Heroism"),
            PotionTemplate::InfraVision => misc::rs2item_name("& %C Potion~| of Infra-Vision"),
            PotionTemplate::Invulnerability => misc::rs2item_name("& %C Potion~| of Invulnerability"),
            PotionTemplate::Learning => misc::rs2item_name("& %C Potion~| of Learning"),
            PotionTemplate::LoseIntelligence => misc::rs2item_name("& %C Potion~| of Lose Intelligence"),
            PotionTemplate::LoseMemories => misc::rs2item_name("& %C Potion~| of Lose Memories"),
            PotionTemplate::LoseWisdom => misc::rs2item_name("& %C Potion~| of Lose Wisdom"),
            PotionTemplate::NeutralizePoison => misc::rs2item_name("& %C Potion~| of Neutralize Poison"),
            PotionTemplate::Poison => misc::rs2item_name("& %C Potion~| of Poison"),
            PotionTemplate::ResistCold => misc::rs2item_name("& %C Potion~| of Resist Cold"),
            PotionTemplate::ResistHeat => misc::rs2item_name("& %C Potion~| of Resist Heat"),
            PotionTemplate::RestoreCharisma => misc::rs2item_name("& %C Potion~| of Restore Charisma"),
            PotionTemplate::RestoreConstitution => misc::rs2item_name("& %C Potion~| of Restore Consitution"),
            PotionTemplate::RestoreDexterity => misc::rs2item_name("& %C Potion~| of Restore Dexterity"),
            PotionTemplate::RestoreIntelligence => misc::rs2item_name("& %C Potion~| of Restore Intelligence"),
            PotionTemplate::RestoreLifeLevels => misc::rs2item_name("& %C Potion~| of Restore Life Levels"),
            PotionTemplate::RestoreMana => misc::rs2item_name("& %C Potion~| of Restore Mana"),
            PotionTemplate::RestoreStrength => misc::rs2item_name("& %C Potion~| of Restore Strength"),
            PotionTemplate::RestoreWisdom => misc::rs2item_name("& %C Potion~| of Restore Wisdom"),
            PotionTemplate::SaltWater => misc::rs2item_name("& %C Potion~| of Salt Water"),
            PotionTemplate::Sleep => misc::rs2item_name("& %C Potion~| of Sleep"),
            PotionTemplate::SlimeMoldJuice => misc::rs2item_name("& %C Potion~| of Slime Mold Juice"),
            PotionTemplate::SlowPoison => misc::rs2item_name("& %C Potion~| of Slow Poison"),
            PotionTemplate::Slowness => misc::rs2item_name("& %C Potion~| of Slowness"),
            PotionTemplate::SuperHeroism => misc::rs2item_name("& %C Potion~| of Super Heroism"),
            PotionTemplate::Ugliness => misc::rs2item_name("& %C Potion~| of Ugliness"),
            PotionTemplate::Water => misc::rs2item_name("& %C Potion~| of Water"),
        }
    }

    fn flags1(&self) -> u64 {
        match self {
            PotionTemplate::Blindness => 0x00000000,
            PotionTemplate::Boldliness => 0x00000020,
            PotionTemplate::Charisma => 0x00000000,
            PotionTemplate::Confusion => 0x00000000,
            PotionTemplate::CureCriticalWounds => 0x00000000,
            PotionTemplate::CureLightWounds => 0x00000000,
            PotionTemplate::CureSeriousWounds => 0x00000000,
            PotionTemplate::DetectInvisible => 0x00000200,
            PotionTemplate::FleaBile => 0x00004000,
            PotionTemplate::GainConstitution => 0x00000000,
            PotionTemplate::GainDexterity => 0x00000000,
            PotionTemplate::GainExperience => 0x00000000,
            PotionTemplate::GainIntelligence => 0x00000000,
            PotionTemplate::GainStrength => 0x00000000,
            PotionTemplate::GainWisdom => 0x00000000,
            PotionTemplate::HasteSelf => 0x00000000,
            PotionTemplate::Healing => 0x00000000,
            PotionTemplate::Heroism => 0x00000008,
            PotionTemplate::InfraVision => 0x00002000,
            PotionTemplate::Invulnerability => 0x00000004,
            PotionTemplate::Learning => 0x00008000,
            PotionTemplate::LoseIntelligence => 0x00000000,
            PotionTemplate::LoseMemories => 0x00000001,
            PotionTemplate::LoseWisdom => 0x00000000,
            PotionTemplate::NeutralizePoison => 0x00000800,
            PotionTemplate::Poison => 0x00000000,
            PotionTemplate::ResistCold => 0x00000100,
            PotionTemplate::ResistHeat => 0x00000080,
            PotionTemplate::RestoreCharisma => 0x00000000,
            PotionTemplate::RestoreConstitution => 0x00000000,
            PotionTemplate::RestoreDexterity => 0x00010000,
            PotionTemplate::RestoreIntelligence => 0x00000000,
            PotionTemplate::RestoreLifeLevels => 0x00000040,
            PotionTemplate::RestoreMana => 0x00001000,
            PotionTemplate::RestoreStrength => 0x00000000,
            PotionTemplate::RestoreWisdom => 0x00000000,
            PotionTemplate::SaltWater => 0x00000002,
            PotionTemplate::Sleep => 0x00000000,
            PotionTemplate::SlowPoison => 0x00000400,
            PotionTemplate::Slowness => 0x00000000,
            PotionTemplate::SuperHeroism => 0x00000010,
            PotionTemplate::Ugliness => 0x00000000,
            PotionTemplate::Water => 0x00000000,
            PotionTemplate::SlimeMoldJuice => 0x00000000,
            PotionTemplate::AppleJuice => 0x00000000,
        }
    }

    fn flags2(&self) -> u64 {
        match self {
            PotionTemplate::Blindness => 0x00080000,
            PotionTemplate::Boldliness => 0x00000000,
            PotionTemplate::Charisma => 0x00000200,
            PotionTemplate::Confusion => 0x00100000,
            PotionTemplate::CureCriticalWounds => 0x70004000,
            PotionTemplate::CureLightWounds => 0x10001000,
            PotionTemplate::CureSeriousWounds => 0x30002000,
            PotionTemplate::DetectInvisible => 0x00000000,
            PotionTemplate::FleaBile => 0x00000000,
            PotionTemplate::GainConstitution => 0x00010000,
            PotionTemplate::GainDexterity => 0x02000000,
            PotionTemplate::GainExperience => 0x00020000,
            PotionTemplate::GainIntelligence => 0x00000008,
            PotionTemplate::GainStrength => 0x00000001,
            PotionTemplate::GainWisdom => 0x00000040,
            PotionTemplate::HasteSelf => 0x00400000,
            PotionTemplate::Healing => 0x70008000,
            PotionTemplate::Heroism => 0x00000000,
            PotionTemplate::InfraVision => 0x00000000,
            PotionTemplate::Invulnerability => 0x00000000,
            PotionTemplate::Learning => 0x00000000,
            PotionTemplate::LoseIntelligence => 0x00000010,
            PotionTemplate::LoseMemories => 0x00000000,
            PotionTemplate::LoseWisdom => 0x00000080,
            PotionTemplate::NeutralizePoison => 0x00000000,
            PotionTemplate::Poison => 0x00000002,
            PotionTemplate::ResistCold => 0x00000000,
            PotionTemplate::ResistHeat => 0x00000000,
            PotionTemplate::RestoreCharisma => 0x00000800,
            PotionTemplate::RestoreConstitution => 0x68000000,
            PotionTemplate::RestoreDexterity => 0x04000000,
            PotionTemplate::RestoreIntelligence => 0x00000020,
            PotionTemplate::RestoreLifeLevels => 0x00000000,
            PotionTemplate::RestoreMana => 0x00000000,
            PotionTemplate::RestoreStrength => 0x00000004,
            PotionTemplate::RestoreWisdom => 0x00000100,
            PotionTemplate::SaltWater => 0x00000000,
            PotionTemplate::Sleep => 0x10040000,
            PotionTemplate::SlowPoison => 0x00000000,
            PotionTemplate::Slowness => 0x00800000,
            PotionTemplate::SuperHeroism => 0x00000000,
            PotionTemplate::Ugliness => 0x00000400,
            PotionTemplate::Water => 0x00800000,
            PotionTemplate::SlimeMoldJuice => 0x30000000,
            PotionTemplate::AppleJuice => 0x00800000,
        }
    }

    fn p1(&self) -> i64 {
        match self {
            PotionTemplate::Blindness => 0,
            PotionTemplate::Boldliness => 0,
            PotionTemplate::Charisma => 0,
            PotionTemplate::Confusion => 50,
            PotionTemplate::CureCriticalWounds => 100,
            PotionTemplate::CureLightWounds => 50,
            PotionTemplate::CureSeriousWounds => 100,
            PotionTemplate::DetectInvisible => 0,
            PotionTemplate::FleaBile => 0,
            PotionTemplate::GainConstitution => 0,
            PotionTemplate::GainDexterity => 0,
            PotionTemplate::GainExperience => 0,
            PotionTemplate::GainIntelligence => 0,
            PotionTemplate::GainStrength => 0,
            PotionTemplate::GainWisdom => 0,
            PotionTemplate::HasteSelf => 0,
            PotionTemplate::Healing => 200,
            PotionTemplate::Heroism => 0,
            PotionTemplate::InfraVision => 0,
            PotionTemplate::Invulnerability => 0,
            PotionTemplate::Learning => 0,
            PotionTemplate::LoseIntelligence => 0,
            PotionTemplate::LoseMemories => 0,
            PotionTemplate::LoseWisdom => 0,
            PotionTemplate::NeutralizePoison => 0,
            PotionTemplate::Poison => 0,
            PotionTemplate::ResistCold => 0,
            PotionTemplate::ResistHeat => 0,
            PotionTemplate::RestoreCharisma => 0,
            PotionTemplate::RestoreConstitution => 0,
            PotionTemplate::RestoreDexterity => 0,
            PotionTemplate::RestoreIntelligence => 0,
            PotionTemplate::RestoreLifeLevels => 0,
            PotionTemplate::RestoreMana => 0,
            PotionTemplate::RestoreStrength => 0,
            PotionTemplate::RestoreWisdom => 0,
            PotionTemplate::SaltWater => 0,
            PotionTemplate::Sleep => 100,
            PotionTemplate::SlowPoison => 0,
            PotionTemplate::Slowness => 50,
            PotionTemplate::SuperHeroism => 0,
            PotionTemplate::Ugliness => 0,
            PotionTemplate::Water => 200,
            PotionTemplate::SlimeMoldJuice => 400,
            PotionTemplate::AppleJuice => 250,
        }
    }

    fn cost(&self) -> i64 {
        match self {
            PotionTemplate::Blindness => 0,
            PotionTemplate::Boldliness => 10,
            PotionTemplate::Charisma => 6500,
            PotionTemplate::Confusion => 0,
            PotionTemplate::CureCriticalWounds => 100,
            PotionTemplate::CureLightWounds => 15,
            PotionTemplate::CureSeriousWounds => 40,
            PotionTemplate::DetectInvisible => 50,
            PotionTemplate::FleaBile => 50,
            PotionTemplate::GainConstitution => 6500,
            PotionTemplate::GainDexterity => 6500,
            PotionTemplate::GainExperience => 15000,
            PotionTemplate::GainIntelligence => 6500,
            PotionTemplate::GainStrength => 6500,
            PotionTemplate::GainWisdom => 6500,
            PotionTemplate::HasteSelf => 155,
            PotionTemplate::Healing => 2500,
            PotionTemplate::Heroism => 35,
            PotionTemplate::InfraVision => 20,
            PotionTemplate::Invulnerability => 12500,
            PotionTemplate::Learning => 200,
            PotionTemplate::LoseIntelligence => 0,
            PotionTemplate::LoseMemories => 0,
            PotionTemplate::LoseWisdom => 0,
            PotionTemplate::NeutralizePoison => 75,
            PotionTemplate::Poison => 0,
            PotionTemplate::ResistCold => 30,
            PotionTemplate::ResistHeat => 30,
            PotionTemplate::RestoreCharisma => 300,
            PotionTemplate::RestoreConstitution => 300,
            PotionTemplate::RestoreDexterity => 300,
            PotionTemplate::RestoreIntelligence => 300,
            PotionTemplate::RestoreLifeLevels => 400,
            PotionTemplate::RestoreMana => 3000,
            PotionTemplate::RestoreStrength => 300,
            PotionTemplate::RestoreWisdom => 300,
            PotionTemplate::SaltWater => 0,
            PotionTemplate::Sleep => 0,
            PotionTemplate::SlowPoison => 25,
            PotionTemplate::Slowness => 0,
            PotionTemplate::SuperHeroism => 100,
            PotionTemplate::Ugliness => 0,
            PotionTemplate::Water => 0,
            PotionTemplate::SlimeMoldJuice => 2,
            PotionTemplate::AppleJuice => 1,
        }
    }

    fn subval(&self) -> i64 {
        match self {
            PotionTemplate::Blindness => 276,
            PotionTemplate::Boldliness => 293,
            PotionTemplate::Charisma => 266,
            PotionTemplate::Confusion => 277,
            PotionTemplate::CureCriticalWounds => 271,
            PotionTemplate::CureLightWounds => 269,
            PotionTemplate::CureSeriousWounds => 270,
            PotionTemplate::DetectInvisible => 297,
            PotionTemplate::FleaBile => 302,
            PotionTemplate::GainConstitution => 273,
            PotionTemplate::GainDexterity => 284,
            PotionTemplate::GainExperience => 274,
            PotionTemplate::GainIntelligence => 260,
            PotionTemplate::GainStrength => 257,
            PotionTemplate::GainWisdom => 263,
            PotionTemplate::HasteSelf => 279,
            PotionTemplate::Healing => 272,
            PotionTemplate::Heroism => 291,
            PotionTemplate::InfraVision => 301,
            PotionTemplate::Invulnerability => 290,
            PotionTemplate::Learning => 287,
            PotionTemplate::LoseIntelligence => 261,
            PotionTemplate::LoseMemories => 288,
            PotionTemplate::LoseWisdom => 264,
            PotionTemplate::NeutralizePoison => 299,
            PotionTemplate::Poison => 258,
            PotionTemplate::ResistCold => 296,
            PotionTemplate::ResistHeat => 295,
            PotionTemplate::RestoreCharisma => 268,
            PotionTemplate::RestoreConstitution => 286,
            PotionTemplate::RestoreDexterity => 285,
            PotionTemplate::RestoreIntelligence => 262,
            PotionTemplate::RestoreLifeLevels => 294,
            PotionTemplate::RestoreMana => 300,
            PotionTemplate::RestoreStrength => 259,
            PotionTemplate::RestoreWisdom => 265,
            PotionTemplate::SaltWater => 289,
            PotionTemplate::Sleep => 275,
            PotionTemplate::SlowPoison => 298,
            PotionTemplate::Slowness => 280,
            PotionTemplate::SuperHeroism => 292,
            PotionTemplate::Ugliness => 267,
            PotionTemplate::Water => 283,
            PotionTemplate::SlimeMoldJuice => 281,
            PotionTemplate::AppleJuice => 282,
        }
    }

    pub fn level(&self) -> u8 {
        match self {
            PotionTemplate::SaltWater => 0,
            PotionTemplate::FleaBile => 0,
            PotionTemplate::Blindness => 0,
            PotionTemplate::Confusion => 0,
            PotionTemplate::CureLightWounds => 0,
            PotionTemplate::Water => 0,
            PotionTemplate::Sleep => 0,
            PotionTemplate::SlimeMoldJuice => 0,
            PotionTemplate::AppleJuice => 0,
            PotionTemplate::ResistCold => 1,
            PotionTemplate::HasteSelf => 1,
            PotionTemplate::Boldliness => 1,
            PotionTemplate::ResistHeat => 1,
            PotionTemplate::Heroism => 1,
            PotionTemplate::SlowPoison => 1,
            PotionTemplate::Slowness =>  1,
            PotionTemplate::CureSeriousWounds => 3,
            PotionTemplate::DetectInvisible => 3,
            PotionTemplate::InfraVision => 3,
            PotionTemplate::Poison => 3,
            PotionTemplate::SuperHeroism => 3,
            PotionTemplate::NeutralizePoison => 5,
            PotionTemplate::CureCriticalWounds => 5,
            PotionTemplate::LoseMemories => 10,
            PotionTemplate::Healing => 12,
            PotionTemplate::Charisma => 25,
            PotionTemplate::Ugliness => 25,
            PotionTemplate::GainConstitution => 25,
            PotionTemplate::GainDexterity => 25,
            PotionTemplate::GainIntelligence => 25,
            PotionTemplate::GainStrength => 25,
            PotionTemplate::GainWisdom => 25,
            PotionTemplate::LoseIntelligence => 25,
            PotionTemplate::RestoreMana => 25,
            PotionTemplate::LoseWisdom =>  25,
            PotionTemplate::RestoreCharisma => 40,
            PotionTemplate::RestoreConstitution => 40,
            PotionTemplate::RestoreDexterity => 40,
            PotionTemplate::RestoreIntelligence => 40,
            PotionTemplate::RestoreStrength => 40,
            PotionTemplate::RestoreWisdom => 40,
            PotionTemplate::RestoreLifeLevels => 40,
            PotionTemplate::Invulnerability => 40,
            PotionTemplate::Learning => 45,
            PotionTemplate::GainExperience => 50,
        }
    }
}
