use misc;
use model;

#[derive(Copy, Clone, Eq, PartialEq, Hash)]
pub enum RingTemplate {
    RingOfGainStrength,
    RingOfGainDexterity,
    RingOfGainConstitution,
    RingOfGainIntelligence,
    RingOfSpeed1,
    RingOfSpeed2,
    RingOfSearching,
    RingOfTeleportation,
    RingOfSlowDigestion,
    RingOfResistFire,
    RingOfResistCold,
    RingOfFeatherFalling,
    RingOfAdornment1,
    RingOfAdornment2,
    RingOfWeakness,
    RingOfLordlyProtectionFire,
    RingOfLordlyProtectionAcid,
    RingOfLordlyProtectionCold,
    RingOfWoe,
    RingOfStupidity,
    RingOfIncreaseDamage,
    RingOfIncreaseToHit,
    RingOfProtection,
    RingOfAggravateMonsters,
    RingOfSeeInvisible,
    RingOfSustainStrength,
    RingOfSustainIntelligence,
    RingOfSustainWisdom,
    RingOfSustainConstitution,
    RingOfSustainDexterity,
    RingOfSustainCharisma,
    RingOfSlaying,
    RingOfGnomekind,
}

impl RingTemplate {
    pub fn iter() -> impl Iterator<Item=RingTemplate> {
        [
            RingTemplate::RingOfGainStrength,
            RingTemplate::RingOfGainDexterity,
            RingTemplate::RingOfGainConstitution,
            RingTemplate::RingOfGainIntelligence,
            RingTemplate::RingOfSpeed1,
            RingTemplate::RingOfSpeed2,
            RingTemplate::RingOfSearching,
            RingTemplate::RingOfTeleportation,
            RingTemplate::RingOfSlowDigestion,
            RingTemplate::RingOfResistFire,
            RingTemplate::RingOfResistCold,
            RingTemplate::RingOfFeatherFalling,
            RingTemplate::RingOfAdornment1,
            RingTemplate::RingOfAdornment2,
            RingTemplate::RingOfWeakness,
            RingTemplate::RingOfLordlyProtectionFire,
            RingTemplate::RingOfLordlyProtectionAcid,
            RingTemplate::RingOfLordlyProtectionCold,
            RingTemplate::RingOfWoe,
            RingTemplate::RingOfStupidity,
            RingTemplate::RingOfIncreaseDamage,
            RingTemplate::RingOfIncreaseToHit,
            RingTemplate::RingOfProtection,
            RingTemplate::RingOfAggravateMonsters,
            RingTemplate::RingOfSeeInvisible,
            RingTemplate::RingOfSustainStrength,
            RingTemplate::RingOfSustainIntelligence,
            RingTemplate::RingOfSustainWisdom,
            RingTemplate::RingOfSustainConstitution,
            RingTemplate::RingOfSustainDexterity,
            RingTemplate::RingOfSustainCharisma,
            RingTemplate::RingOfSlaying,
            RingTemplate::RingOfGnomekind,
        ].iter().copied()
    }

    pub fn create(&self) -> model::Item {
        model::Item {
            name: misc::rs2item_name(self.name()),
            tval: model::ItemType::Ring as u8,
            flags: 0,
            flags2: self.flags2(),
            p1: self.p1(),
            cost: self.cost() * model::Currency::Gold.value(),
            subval: self.subval(),
            weight: 2,
            number: 1,
            tohit: 0,
            todam: 0,
            ac: 0,
            toac: self.to_ac(),
            damage: misc::rs2item_damage("0d0"),
            level: 0,
            identified: 0,
        }
    }

    fn name(&self) -> &str {
        match self {
            RingTemplate::RingOfGainStrength => "& %r ring| of gain strength^ (%p1)",
            RingTemplate::RingOfGainDexterity => "& %r ring| of gain dexterity^ (%p1)",
            RingTemplate::RingOfGainConstitution => "& %r ring| of gain constitution^ (%p1)",
            RingTemplate::RingOfGainIntelligence => "& %r ring| of gain intelligence^ (%p1)",
            RingTemplate::RingOfSpeed1 => "& %r ring| of speed^ (%p1)",
            RingTemplate::RingOfSpeed2 => "& %r ring| of speed^ (%p1)",
            RingTemplate::RingOfSearching => "& %r ring| of searching^ (%p1)",
            RingTemplate::RingOfTeleportation => "& %r ring| of teleportation^",
            RingTemplate::RingOfSlowDigestion => "& %r ring| of slow digestion^",
            RingTemplate::RingOfResistFire => "& %r ring| of resist fire^",
            RingTemplate::RingOfResistCold => "& %r ring| of resist cold^",
            RingTemplate::RingOfFeatherFalling => "& %r ring| of feather falling^",
            RingTemplate::RingOfAdornment1 => "& %r ring| of adornment^",
            RingTemplate::RingOfAdornment2 => "& %r ring| of adornment^",
            RingTemplate::RingOfWeakness => "& %r ring| of weakness^",
            RingTemplate::RingOfLordlyProtectionFire => "& %r ring| of lordly protection (fire)^",
            RingTemplate::RingOfLordlyProtectionAcid => "& %r ring| of lordly protection (acid)^",
            RingTemplate::RingOfLordlyProtectionCold => "& %r ring| of lordly protection (cold)^",
            RingTemplate::RingOfWoe => "& %r ring| of woe^",
            RingTemplate::RingOfStupidity => "& %r ring| of stupidity^",
            RingTemplate::RingOfIncreaseDamage => "& %r ring| of increase damage^ (%p3)",
            RingTemplate::RingOfIncreaseToHit => "& %r ring| of increase to-hit^ (%p2)",
            RingTemplate::RingOfProtection => "& %r ring| of protection^ [%p4]",
            RingTemplate::RingOfAggravateMonsters => "& %r ring| of aggravate monster^",
            RingTemplate::RingOfSeeInvisible => "& %r ring| of see invisible^",
            RingTemplate::RingOfSustainStrength => "& %r ring| of sustain strength^",
            RingTemplate::RingOfSustainIntelligence => "& %r ring| of sustain intelligence^",
            RingTemplate::RingOfSustainWisdom => "& %r ring| of sustain wisdom^",
            RingTemplate::RingOfSustainConstitution => "& %r ring| of sustain constitution^",
            RingTemplate::RingOfSustainDexterity => "& %r ring| of sustain dexterity^",
            RingTemplate::RingOfSustainCharisma => "& %r ring| of sustain charisma^",
            RingTemplate::RingOfSlaying => "& %r ring| of slaying^",
            RingTemplate::RingOfGnomekind => "& %r ring| of gnomekind^",
        }
    }

    fn flags2(&self) -> u64 {
        match self {
            RingTemplate::RingOfGainStrength => 0x00000001,
            RingTemplate::RingOfGainDexterity => 0x00000002,
            RingTemplate::RingOfGainConstitution => 0x00000004,
            RingTemplate::RingOfGainIntelligence => 0x00000008,
            RingTemplate::RingOfSpeed1 => 0x00001000,
            RingTemplate::RingOfSpeed2 => 0x00001000,
            RingTemplate::RingOfSearching => 0x00000040,
            RingTemplate::RingOfTeleportation => 0x80000400,
            RingTemplate::RingOfSlowDigestion => 0x00000080,
            RingTemplate::RingOfResistFire => 0x00080000,
            RingTemplate::RingOfResistCold => 0x00200000,
            RingTemplate::RingOfFeatherFalling => 0x04000000,
            RingTemplate::RingOfAdornment1 => 0x00000000,
            RingTemplate::RingOfAdornment2 => 0x00000000,
            RingTemplate::RingOfWeakness => 0x80000001,
            RingTemplate::RingOfLordlyProtectionFire => 0x00080000,
            RingTemplate::RingOfLordlyProtectionAcid => 0x00100000,
            RingTemplate::RingOfLordlyProtectionCold => 0x00200000,
            RingTemplate::RingOfWoe => 0x80000600,
            RingTemplate::RingOfStupidity => 0x80000008,
            RingTemplate::RingOfIncreaseDamage => 0x00000000,
            RingTemplate::RingOfIncreaseToHit => 0x00000000,
            RingTemplate::RingOfProtection => 0x00000000,
            RingTemplate::RingOfAggravateMonsters => 0x80000200,
            RingTemplate::RingOfSeeInvisible => 0x01000000,
            RingTemplate::RingOfSustainStrength => 0x00400000,
            RingTemplate::RingOfSustainIntelligence => 0x00400000,
            RingTemplate::RingOfSustainWisdom => 0x00400000,
            RingTemplate::RingOfSustainConstitution => 0x00400000,
            RingTemplate::RingOfSustainDexterity => 0x00400000,
            RingTemplate::RingOfSustainCharisma => 0x00400000,
            RingTemplate::RingOfSlaying => 0x00000000,
            RingTemplate::RingOfGnomekind => 0x00400088,
        }
    }

    fn p1(&self) -> i64 {
        match self {
            RingTemplate::RingOfGainStrength => 0,
            RingTemplate::RingOfGainDexterity => 0,
            RingTemplate::RingOfGainConstitution => 0,
            RingTemplate::RingOfGainIntelligence => 0,
            RingTemplate::RingOfSpeed1 => 0,
            RingTemplate::RingOfSpeed2 => 0,
            RingTemplate::RingOfSearching => 0,
            RingTemplate::RingOfTeleportation => 0,
            RingTemplate::RingOfSlowDigestion => 0,
            RingTemplate::RingOfResistFire => 0,
            RingTemplate::RingOfResistCold => 0,
            RingTemplate::RingOfFeatherFalling => 0,
            RingTemplate::RingOfAdornment1 => 0,
            RingTemplate::RingOfAdornment2 => 0,
            RingTemplate::RingOfWeakness => -5,
            RingTemplate::RingOfLordlyProtectionFire => 0,
            RingTemplate::RingOfLordlyProtectionAcid => 0,
            RingTemplate::RingOfLordlyProtectionCold => 0,
            RingTemplate::RingOfWoe => -5,
            RingTemplate::RingOfStupidity => -5,
            RingTemplate::RingOfIncreaseDamage => 0,
            RingTemplate::RingOfIncreaseToHit => 0,
            RingTemplate::RingOfProtection => 0,
            RingTemplate::RingOfAggravateMonsters => 0,
            RingTemplate::RingOfSeeInvisible => 0,
            RingTemplate::RingOfSustainStrength => 1,
            RingTemplate::RingOfSustainIntelligence => 2,
            RingTemplate::RingOfSustainWisdom => 3,
            RingTemplate::RingOfSustainConstitution => 4,
            RingTemplate::RingOfSustainDexterity => 5,
            RingTemplate::RingOfSustainCharisma => 6,
            RingTemplate::RingOfSlaying => 6,
            RingTemplate::RingOfGnomekind => 2,
        }
    }

    fn cost(&self) -> i64 {
        match self {
            RingTemplate::RingOfGainStrength => 400,
            RingTemplate::RingOfGainDexterity => 400,
            RingTemplate::RingOfGainConstitution => 400,
            RingTemplate::RingOfGainIntelligence => 350,
            RingTemplate::RingOfSpeed1 => 8000,
            RingTemplate::RingOfSpeed2 => 1,
            RingTemplate::RingOfSearching => 250,
            RingTemplate::RingOfTeleportation => 0,
            RingTemplate::RingOfSlowDigestion => 250,
            RingTemplate::RingOfResistFire => 250,
            RingTemplate::RingOfResistCold => 250,
            RingTemplate::RingOfFeatherFalling => 200,
            RingTemplate::RingOfAdornment1 => 20,
            RingTemplate::RingOfAdornment2 => 30,
            RingTemplate::RingOfWeakness => 0,
            RingTemplate::RingOfLordlyProtectionFire => 1200,
            RingTemplate::RingOfLordlyProtectionAcid => 1200,
            RingTemplate::RingOfLordlyProtectionCold => 1200,
            RingTemplate::RingOfWoe => 0,
            RingTemplate::RingOfStupidity => 0,
            RingTemplate::RingOfIncreaseDamage => 100,
            RingTemplate::RingOfIncreaseToHit => 100,
            RingTemplate::RingOfProtection => 100,
            RingTemplate::RingOfAggravateMonsters => 0,
            RingTemplate::RingOfSeeInvisible => 340,
            RingTemplate::RingOfSustainStrength => 750,
            RingTemplate::RingOfSustainIntelligence => 600,
            RingTemplate::RingOfSustainWisdom => 600,
            RingTemplate::RingOfSustainConstitution => 750,
            RingTemplate::RingOfSustainDexterity => 750,
            RingTemplate::RingOfSustainCharisma => 500,
            RingTemplate::RingOfSlaying => 1000,
            RingTemplate::RingOfGnomekind => 2000,
        }
    }

    fn subval(&self) -> i64 {
        match self {
            RingTemplate::RingOfGainStrength => 1,
            RingTemplate::RingOfGainDexterity => 2,
            RingTemplate::RingOfGainConstitution => 3,
            RingTemplate::RingOfGainIntelligence => 4,
            RingTemplate::RingOfSpeed1 => 7,
            RingTemplate::RingOfSpeed2 => 35,
            RingTemplate::RingOfSearching => 8,
            RingTemplate::RingOfTeleportation => 9,
            RingTemplate::RingOfSlowDigestion => 10,
            RingTemplate::RingOfResistFire => 11,
            RingTemplate::RingOfResistCold => 12,
            RingTemplate::RingOfFeatherFalling => 13,
            RingTemplate::RingOfAdornment1 => 14,
            RingTemplate::RingOfAdornment2 => 15,
            RingTemplate::RingOfWeakness => 16,
            RingTemplate::RingOfLordlyProtectionFire => 17,
            RingTemplate::RingOfLordlyProtectionAcid => 18,
            RingTemplate::RingOfLordlyProtectionCold => 19,
            RingTemplate::RingOfWoe => 20,
            RingTemplate::RingOfStupidity => 21,
            RingTemplate::RingOfIncreaseDamage => 22,
            RingTemplate::RingOfIncreaseToHit => 23,
            RingTemplate::RingOfProtection => 24,
            RingTemplate::RingOfAggravateMonsters => 25,
            RingTemplate::RingOfSeeInvisible => 26,
            RingTemplate::RingOfSustainStrength => 27,
            RingTemplate::RingOfSustainIntelligence => 28,
            RingTemplate::RingOfSustainWisdom => 29,
            RingTemplate::RingOfSustainConstitution => 30,
            RingTemplate::RingOfSustainDexterity => 31,
            RingTemplate::RingOfSustainCharisma => 32,
            RingTemplate::RingOfSlaying => 33,
            RingTemplate::RingOfGnomekind => 34,
        }
    }

    fn to_ac(&self) -> i16 {
        match self {
            RingTemplate::RingOfGainStrength => 0,
            RingTemplate::RingOfGainDexterity => 0,
            RingTemplate::RingOfGainConstitution => 0,
            RingTemplate::RingOfGainIntelligence => 0,
            RingTemplate::RingOfSpeed1 => 0,
            RingTemplate::RingOfSpeed2 => 0,
            RingTemplate::RingOfSearching => 0,
            RingTemplate::RingOfTeleportation => 0,
            RingTemplate::RingOfSlowDigestion => 0,
            RingTemplate::RingOfResistFire => 0,
            RingTemplate::RingOfResistCold => 0,
            RingTemplate::RingOfFeatherFalling => 0,
            RingTemplate::RingOfAdornment1 => 0,
            RingTemplate::RingOfAdornment2 => 0,
            RingTemplate::RingOfWeakness => 0,
            RingTemplate::RingOfLordlyProtectionFire => 5,
            RingTemplate::RingOfLordlyProtectionAcid => 5,
            RingTemplate::RingOfLordlyProtectionCold => 5,
            RingTemplate::RingOfWoe => -3,
            RingTemplate::RingOfStupidity => 0,
            RingTemplate::RingOfIncreaseDamage => 0,
            RingTemplate::RingOfIncreaseToHit => 0,
            RingTemplate::RingOfProtection => 0,
            RingTemplate::RingOfAggravateMonsters => 0,
            RingTemplate::RingOfSeeInvisible => 0,
            RingTemplate::RingOfSustainStrength => 0,
            RingTemplate::RingOfSustainIntelligence => 0,
            RingTemplate::RingOfSustainWisdom => 0,
            RingTemplate::RingOfSustainConstitution => 0,
            RingTemplate::RingOfSustainDexterity => 0,
            RingTemplate::RingOfSustainCharisma => 0,
            RingTemplate::RingOfSlaying => 0,
            RingTemplate::RingOfGnomekind => 0,
        }
    }

    fn level(&self) -> u8 {
        match self {
            RingTemplate::RingOfGainStrength => 30,
            RingTemplate::RingOfGainDexterity => 30,
            RingTemplate::RingOfGainConstitution => 30,
            RingTemplate::RingOfGainIntelligence => 30,
            RingTemplate::RingOfSpeed1 => 50,
            RingTemplate::RingOfSpeed2 => 5,
            RingTemplate::RingOfSearching => 7,
            RingTemplate::RingOfTeleportation => 7,
            RingTemplate::RingOfSlowDigestion => 7,
            RingTemplate::RingOfResistFire => 14,
            RingTemplate::RingOfResistCold => 14,
            RingTemplate::RingOfFeatherFalling => 7,
            RingTemplate::RingOfAdornment1 => 7,
            RingTemplate::RingOfAdornment2 => 7,
            RingTemplate::RingOfWeakness => 7,
            RingTemplate::RingOfLordlyProtectionFire => 50,
            RingTemplate::RingOfLordlyProtectionAcid => 50,
            RingTemplate::RingOfLordlyProtectionCold => 50,
            RingTemplate::RingOfWoe => 50,
            RingTemplate::RingOfStupidity => 20,
            RingTemplate::RingOfIncreaseDamage => 20,
            RingTemplate::RingOfIncreaseToHit => 20,
            RingTemplate::RingOfProtection => 7,
            RingTemplate::RingOfAggravateMonsters => 7,
            RingTemplate::RingOfSeeInvisible => 40,
            RingTemplate::RingOfSustainStrength => 44,
            RingTemplate::RingOfSustainIntelligence => 44,
            RingTemplate::RingOfSustainWisdom => 44,
            RingTemplate::RingOfSustainConstitution => 44,
            RingTemplate::RingOfSustainDexterity => 44,
            RingTemplate::RingOfSustainCharisma => 7,
            RingTemplate::RingOfSlaying => 50,
            RingTemplate::RingOfGnomekind => 40,
        }
    }
}
