use types::{ Spell };

pub fn spell(level: usize) -> Spell {
    match level {
        1  => Spell { name: "Magic Missile", level: 3, mana: 1, fail: 30},
        2  => Spell { name: "Detect Monsters", level: 3, mana: 2, fail: 35},
        3  => Spell { name: "Phase Door", level: 3, mana: 2, fail: 35},
        4  => Spell { name: "Light Area", level: 5, mana: 3, fail: 26},
        5  => Spell { name: "Cure Light Wounds", level: 5, mana: 3, fail: 25},
        6  => Spell { name: "Find Hidden Traps/Doors", level: 7, mana: 4, fail: 45},
        7  => Spell { name: "Stinking Cloud", level: 7, mana: 6, fail: 40},
        8  => Spell { name: "Confusion", level: 9, mana: 6, fail: 40},
        9  => Spell { name: "Lightning Bolt", level: 9, mana: 7, fail: 40},
        10 => Spell { name: "Trap/Door Destruction", level: 11, mana: 8, fail: 45},
        11 => Spell { name: "Sleep I", level: 11, mana: 8, fail: 40},
        12 => Spell { name: "Cure Poison", level: 13, mana: 9, fail: 45},
        13 => Spell { name: "Shadow Door", level: 13, mana: 10, fail: 45},
        14 => Spell { name: "Remove Curse", level: 15, mana: 11, fail: 55},
        15 => Spell { name: "Frost Bolt", level: 15, mana: 12, fail: 50},
        16 => Spell { name: "Create Food", level: 17, mana: 12, fail: 55},
        17 => Spell { name: "Infravision", level: 17, mana: 12, fail: 50},
        18 => Spell { name: "Invisibility", level: 17, mana: 13, fail: 50},
        19 => Spell { name: "Turn Stone to Mud", level: 19, mana: 15, fail: 50},
        20 => Spell { name: "Recharge Item I", level: 19, mana: 17, fail: 90},
        21 => Spell { name: "Sleep II", level: 21, mana: 17, fail: 55},
        22 => Spell { name: "Phantasmal Force", level: 21, mana: 19, fail: 50},
        23 => Spell { name: "Polymorph Other", level: 23, mana: 19, fail: 60},
        24 => Spell { name: "Identify", level: 23, mana: 25, fail: 95},
        25 => Spell { name: "Ring of Frost", level: 25, mana: 19, fail: 60},
        26 => Spell { name: "Sleep III", level: 25, mana: 20, fail: 60},
        27 => Spell { name: "Hold Monster", level: 27, mana: 20, fail: 50},
        28 => Spell { name: "Fire Bolt", level: 27, mana: 20, fail: 60},
        29 => Spell { name: "Slow Creature", level: 29, mana: 21, fail: 65},
        30 => Spell { name: "Protection From Magic", level: 31, mana: 21, fail: 70},
        31 => Spell { name: "Frost Ball", level: 31, mana: 21, fail: 65},
        32 => Spell { name: "Death Spell", level: 33, mana: 21, fail: 60},
        33 => Spell { name: "Ring of Fire", level: 35, mana: 21, fail: 65},
        34 => Spell { name: "Recharge Item II", level: 35, mana: 23, fail: 95},
        35 => Spell { name: "Teleport Other", level: 37, mana: 25, fail: 70},
        36 => Spell { name: "Haste Self", level: 37, mana: 25, fail: 75},
        37 => Spell { name: "Fire Ball", level: 39, mana: 27, fail: 80},
        38 => Spell { name: "Power Word: Destruction", level: 39, mana: 30, fail: 95},
        _  => Spell { name: "", level: 99, mana: 99, fail: 0},
    }
}
