use types::{ Spell };

pub fn spell(level: usize) -> Spell {
    match level {
        0  => Spell { name: "Detect Evil", level: 1, mana: 1, fail: 30 },
        1  => Spell { name: "Cure Light Wounds", level: 2, mana: 2, fail: 35 },
        2  => Spell { name: "Bless", level: 3, mana: 3, fail: 35 },
        3  => Spell { name: "Remove Fear", level: 5, mana: 3, fail: 35 },
        4  => Spell { name: "Call Light", level: 5, mana: 4, fail: 35 },
        5  => Spell { name: "Find Traps", level: 7, mana: 5, fail: 40 },
        6  => Spell { name: "Detect Doors/Stairs", level: 7, mana: 5, fail: 40 },
        7  => Spell { name: "Slow Poison", level: 9, mana: 7, fail: 40 },
        8  => Spell { name: "Blind Creature", level: 9, mana: 7, fail: 40 },
        9  => Spell { name: "Portal", level: 9, mana: 8, fail: 40 },
        10 => Spell { name: "Cure Medium Wounds", level: 11, mana: 9, fail: 40 },
        11 => Spell { name: "Ray of Sanctification", level: 11, mana: 9, fail: 40 },
        12 => Spell { name: "Heroism", level: 11, mana: 9, fail: 40 },
        13 => Spell { name: "Sanctuary", level: 13, mana: 10, fail: 45 },
        14 => Spell { name: "Remove Curse", level: 13, mana: 11, fail: 45 },
        15 => Spell { name: "Resist Heat and Cold", level: 15, mana: 13, fail: 45 },
        16 => Spell { name: "Silence", level: 15, mana: 13, fail: 45 },
        17 => Spell { name: "Resist Petrification", level: 15, mana: 13, fail: 50 },
        18 => Spell { name: "Neutralize Poison", level: 15, mana: 15, fail: 50 },
        19 => Spell { name: "Cure Serious Wounds", level: 17, mana: 15, fail: 50 },
        20 => Spell { name: "Chant", level: 17, mana: 15, fail: 70 },
        21 => Spell { name: "Sense Invisible", level: 19, mana: 15, fail: 50 },
        22 => Spell { name: "Protection from Evil", level: 19, mana: 15, fail: 50 },
        23 => Spell { name: "Earthquake", level: 21, mana: 17, fail: 50 },
        24 => Spell { name: "Create Food and Drink", level: 21, mana: 10, fail: 45 },
        25 => Spell { name: "Sense Surroundings", level: 23, mana: 17, fail: 50 },
        26 => Spell { name: "Orb of Draining", level: 23, mana: 20, fail: 85 },
        27 => Spell { name: "Cure Critical Wounds", level: 25, mana: 20, fail: 50 },
        28 => Spell { name: "Turn Undead", level: 25, mana: 21, fail: 50 },
        29 => Spell { name: "Holy Prayer", level: 27, mana: 22, fail: 50 },
        30 => Spell { name: "Dispel Undead", level: 29, mana: 24, fail: 60 },
        31 => Spell { name: "Resist Paralysis", level: 31, mana: 26, fail: 55 },
        32 => Spell { name: "Blade Barrier", level: 33, mana: 27, fail: 60 },
        33 => Spell { name: "Dispel Evil", level: 35, mana: 28, fail: 70 },
        34 => Spell { name: "Heal", level: 37, mana: 32, fail: 75 },
        35 => Spell { name: "Resist Magic", level: 38, mana: 32, fail: 75 },
        36 => Spell { name: "Holy Thunder", level: 39, mana: 30, fail: 80 },
        _  => Spell { name: "", level: 99, mana: 99, fail: 0 },
    }
}
