use types::{ Spell };

pub fn spell(level: usize) -> Spell {
    match level {
        0  => Spell { name: "Detect Evil", level: 1, mana: 1, fail: 10 },
        1  => Spell { name: "Cure Light Wounds", level: 1, mana: 2, fail: 15 },
        2  => Spell { name: "Bless", level: 1, mana: 2, fail: 20 },
        3  => Spell { name: "Remove Fear", level: 1, mana: 2, fail: 25 },
        4  => Spell { name: "Call Light", level: 3, mana: 2, fail: 25 },
        5  => Spell { name: "Find Traps", level: 3, mana: 3, fail: 27 },
        6  => Spell { name: "Detect Doors/Stairs", level: 3, mana: 3, fail: 27 },
        7  => Spell { name: "Slow Poison", level: 3, mana: 3, fail: 28 },
        8  => Spell { name: "Blind Creature", level: 5, mana: 4, fail: 29 },
        9  => Spell { name: "Portal", level: 5, mana: 4, fail: 30 },
        10 => Spell { name: "Cure Medium Wounds", level: 5, mana: 4, fail: 32 },
        11 => Spell { name: "Ray of Sanctification", level: 5, mana: 4, fail: 40 },
        12 => Spell { name: "Heroism", level: 7, mana: 4, fail: 40 },
        13 => Spell { name: "Sanctuary", level: 7, mana: 5, fail: 36 },
        14 => Spell { name: "Remove Curse", level: 7, mana: 6, fail: 38 },
        15 => Spell { name: "Resist Heat and Cold", level: 7, mana: 7, fail: 38 },
        16 => Spell { name: "Silence", level: 9, mana: 7, fail: 40 },
        17 => Spell { name: "Resist Petrification", level: 9, mana: 7, fail: 40 },
        18 => Spell { name: "Neutralize Poison", level: 9, mana: 7, fail: 38 },
        19 => Spell { name: "Cure Serious Wounds", level: 9, mana: 7, fail: 40 },
        20 => Spell { name: "Chant", level: 11, mana: 8, fail: 34 },
        21 => Spell { name: "Sense Invisible", level: 11, mana: 8, fail: 42 },
        22 => Spell { name: "Protection from Evil", level: 11, mana: 8, fail: 42 },
        23 => Spell { name: "Earthquake", level: 11, mana: 9, fail: 55 },
        24 => Spell { name: "Create Food and Drink", level: 13, mana: 9, fail: 38 },
        25 => Spell { name: "Sense Surroundings", level: 13, mana: 10, fail: 45 },
        26 => Spell { name: "Orb of Draining", level: 13, mana: 10, fail: 58 },
        27 => Spell { name: "Cure Critical Wounds", level: 15, mana: 11, fail: 45 },
        28 => Spell { name: "Turn Undead", level: 15, mana: 12, fail: 50 },
        29 => Spell { name: "Holy Prayer", level: 17, mana: 14, fail: 50 },
        30 => Spell { name: "Dispel Undead", level: 17, mana: 14, fail: 55 },
        31 => Spell { name: "Resist Paralysis", level: 19, mana: 15, fail: 55 },
        32 => Spell { name: "Blade Barrier", level: 21, mana: 16, fail: 60 },
        33 => Spell { name: "Dispel Evil", level: 23, mana: 18, fail: 70 },
        34 => Spell { name: "Heal", level: 25, mana: 20, fail: 60 },
        35 => Spell { name: "Resist Magic", level: 27, mana: 22, fail: 80 },
        36 => Spell { name: "Holy of Thunder", level: 30, mana: 23, fail: 70 },
        37 => Spell { name: "Glyph of Warding", level: 33, mana: 24, fail: 90 },
        38 => Spell { name: "Hero's Feast", level: 35, mana: 28, fail: 95 },
        39 => Spell { name: "Holy Word", level: 39, mana: 32, fail: 99 },
        _  => Spell { name: "", level: 99, mana: 99, fail: 0},
    }
}
